### ISSUE TITLE
Implement message queueing when no connection is available

### ISSUE THREAD

**Issue by binarybucks** [owntracks/android#1]

**Comment by binarybucks** [comment]
@jpmens I need your input on queueing behavior. 

Pre 0.5.7 will try to publish a message and throw it away if it is not published within 30 seconds (actually, just the publish method has to return within 30 seconds without throwing an error, an actual PUBACK is never checked so the current behavior is meh anyway). 

With 0.5.7 I'm tweaking the BrokerService to queue messages in memory, therefore I've implemented the following method in pseudocode: 

```
Queue backlog; 

void publish(Message message)
  if(!backlog.contains(message)
    backlog.push(message); 
  try {
     connection.publish(message);
  } catch (MqttException e){
    // MARK
  }
}

void deliverBacklog(){
   for message in backlog
      publish(message)
}

// Called by MQTT client on PUBACK
void deliveryComplete() {
   backlog.remove(messag);
}
```

The reason I have to implement this, is that the Paho client a) throws an error if the client is not connected during publish and does not store it in it's persistence store and b) it clears the persistence store when the client connects anew. 

Now there are several questions:
1) When to call deliverBacklog? Currently I'm calling it when the connection is newly established. This might be another broker as the one to which the messages were originally targeted at. 
2) What to do during ```MARK```? 
The publish can throw all kinds of errors, one of them being REASON_CODE_CLIENT_NOT_CONNECTED? Shall I generally ignore publish errors and queue the item no matter what or shall I throw it away on certain ones (full list is at http://www.eclipse.org/paho/files/javadoc/org/eclipse/paho/client/mqttv3/MqttException.html)

3) How to handle message order? Shall I likewise queue new messages until the backlog is empty to preserve publish order or don't we care about this?

**Comment by jpmens** [comment]
1. It sounds sensible to deliver when connection is clearly re-established, but you may wish to consult with @ckrey on how he does it exactly.
2. If possible, I'd like to see messages published in any case, even if it can be a bit until they arrive at broker (this is important for people who want to keep historic data). A thought that occurs whilst browsing the list you link to: I assume there will be cases where it becomes impossible. Could `Queue` contain a TTL which is decremented at each try and you throw the message away when it reaches 0? Or perhaps, instead of TTL a RETRYCOUNTER which starts at, say, 10, and when reaches 0 the message is doomed?
3. I don't think the order matters (except for Waypoint events). Of course it would be nice to keep in `tst` order, but I don't really think this is vital to have.

**Comment by binarybucks** [comment]
2) Yes. RETRYCOUNTER is possible and easy. 
3) Keeping order for waypoint events is harder. The service doesn't really now what it publishes. Its just strings and parameters at this level.
