### ISSUE TITLE
Unable to locate my phone if Google location accuracy is disabled 

### ISSUE THREAD

**Issue by AlertSubject** [owntracks/android#1102]
(this behavior only starts after the app is opened the first time. After a reboot or having crashed in the background for example) 

The apps keeps prompting me to enable Google location accuracy when I hit the locate button. 
Previously this wasn't necessary since the app will locate me in the background regardless

Recently this behavior has changed and owntracks refuses to find my location + sending it to a server unless location accuracy is enabled. Other apps have no issues finding my location

Enabling it causes owntracks to immediately find me and send said location to server. 
It's possible to disable location accuracy after a few hours and not losing the ability to be tracked by the app

Android 11, latest OT beta, oneplus 9 pro

**Comment by growse** [comment]
This sounds like the behaviour that was introduced in https://github.com/owntracks/android/commit/c196ea7755b8a808ff57b67c451e5f3049722216 as a result of people disabling location services on their device and then being confused by why OT stopped working. So now it checks to see if location services is enabled when you foreground the app.

I guess there's a potential refinement here, whereby OT only does this check on first start. If the user decides to disable location accuracy (or location alltogether), OT won't try and detect & notify?

**Comment by growse** [comment]
Sure, I understand. The problem is that I don't think it's possible for OT to distinguish between Location off, Location on but location accuracy off, and everything on, using the [LocationSettingsRequest](https://developers.google.com/android/reference/com/google/android/gms/location/LocationSettingsRequest.Builder).

Maybe an advanced preference called "don't bother me about location apparently being disabled"?

**Comment by AlertSubject** [comment]
I'm not a developer at all so I don't know about the inner workings of all that but other maps apps usually just tell you that your GPS is disabled without asking about Google location accuracy
For example when opening magic earth, it'll immediately check if GPS is enabled
But no location accuracy prompt if you have it disabled
It's just telling you to enable GPS in the settings

**Comment by growse** [comment]
I'll do some investigating. If Magic Earth is open source, I'd be interested to look at what API they're using to detect location enablement that's independent of the location accuracy setting.

My brain is leaky though, so it could well be that there's a very simple Android API that can provide exactly this that I've forgotten about. If so, I think it makes sense to switch to that, because your use case is valid.

**Comment by AlertSubject** [comment]
Magic earth is not open source
But organic maps is and their startup detection is exactly the same as magic earth
