### ISSUE TITLE
"mqtt ciphertext failed verification" with symmetric payload encryption activated.

### ISSUE THREAD

**Issue by s256** [owntracks/android#1124]
Hi all,

I set up owntracks with MQTT and mutual TLS for an iPhone and my Pixel3. On the iPhone everything works fine, but on the Pixel I receive the following error in the app:

 `MQTT Error: ciphertext failed verification`
While on mosquitto I see: `Socket error on client pixel3, disconnecting.` 
Debug mode in mosquitto does not give me any more details.
As soon as I remove the symmetric key in the Android config, the sync works just fine.

I added the the key to the LMDB `echo "user-pixel3 *supersecretkey*"| ocat --load=keys` and I can push the waypoints(regions) successfully - as seen in the ot-recorder logs.

I tried to use a fresh client-id, fresh device name and ID. Nothing. For now it looks the problem only exists with Android, but to be honest - I am not sure I missed a step or something in the Docs is missing. 

`mosquitto. conf`:
```
user mosquitto
# this is TLS
listener 8883

# per_listener_settings true
allow_anonymous false

require_certificate true
use_identity_as_username true
 
certfile /etc/mosquitto/server.crt
keyfile  /etc/mosquitto/server.pem
cafile   /etc/mosquitto/ca-chain.crt
crlfile  /etc/mosquitto/crl.crt
 
ciphers ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4
 
connection_messages true
```

`ot-recorder`:
```
OTR_HOST="foo.bar.hostname"
OTR_PORT=8883
OTR_CERTFILE="/etc/owntracks/client.crt"
OTR_KEYFILE="/etc/owntracks/client.pem"
OTR_CAFILE="/etc/owntracks/ca-chain.crt"
OTR_TOPICS="owntracks/#"
```
`app-config`:
```
{
  "_type" : "configuration",
  "waypoints" : [ {
    "_type" : "waypoint",
    "desc" : "Home",
    "lat" : 23.2115485,
    "lon" : 11.8003542,
    "rad" : 60,
    "tst" : 1635837208
  }],
  "_build" : 24317,
  "autostartOnBoot" : true,
  "cleanSession" : true,
  "clientId" : "pixel3",
  "cmd" : true,
  "connectionTimeoutSeconds" : 30,
  "debugLog" : false,
  "deviceId" : "pixel3",
  "experimentalFeatures" : [ ],
  "fusedRegionDetection" : true,
  "host" : "foo.bar.hostname",
  "ignoreInaccurateLocations" : 0,
  "ignoreStaleLocations" : 0.0,
  "info" : true,
  "keepalive" : 900,
  "locatorDisplacement" : 500,
  "locatorInterval" : 300,
  "locatorPriority" : 2,
  "mode" : 0,
  "monitoring" : 1,
  "moveModeLocatorInterval" : 10,
  "mqttProtocolLevel" : 4,
  "notificationEvents" : true,
  "notificationGeocoderErrors" : true,
  "notificationHigherPriority" : false,
  "notificationLocation" : true,
  "opencageApiKey" : "",
  "password" : "",
  "ping" : 30,
  "port" : 8883,
  "pubExtendedData" : true,
  "pubQos" : 1,
  "pubRetain" : true,
  "pubTopicBase" : "owntracks/%u/%d",
  "remoteConfiguration" : false,
  "reverseGeocodeProvider" : "Device",
  "sub" : true,
  "subQos" : 2,
  "subTopic" : "owntracks/+/+",
  "theme" : 2,
  "tid" : "02",
  "tls" : true,
  "tlsCaCrt" : "ca-chain.cert.pem",
  "tlsClientCrt" : "client.p12",
  "tlsClientCrtPassword" : "*SUPERSECRET",
  "username" : "",
  "ws" : false
}
```

* **App build number**: 2.4.3(24317) Google Play
* **Android version**:  12
* **Device**:  Pixel3

**Comment by growse** [comment]
I'm having some difficulty reproducing this. I've just got the current version running with a client cert, publishing locations to mosquitto 2.0.14 and then onto the current OT-R. I used `mkcert` to generate the client cert p12 (with the CN-setting patch from https://github.com/FiloSottile/mkcert/pull/258/files), so my `tlsClientCrtPassword` is `changeit`, and I've set a symmetric encryption of `secret` in the app, and loaded that into OTR via `ocat`:

```
$ ocat --dump=keys
android-genericx8664 secret
```

I don't seem to see any error - the messages get published and I can track the route in the OTR web interface, while seeing `encrypted` type messages via `mosquitto_sub`. 

The `MQTT Error: ciphertext failed verification` along with the `Socket error on client pixel3, disconnecting.` message seems to imply that this is a TLS issue, rather than a symmetric encyrption  / OTR problem.

>  As soon as I remove the symmetric key in the Android config, the sync works just fine.

Do you mean the "Encryption Key" in the Advanced Preferences, or the "Client Certificate Password" in the Host Security preferences?

**Comment by growse** [comment]
I took another look at this: `ciphertext failed verification` is an error from `libsodium` that we use for symmetric encryption. The `MQTT Error` is a bug, due to effectively not handling the error properly when the message is received. The MQTT client triggers a `connection Lost` event if there's an unhandled exception thrown in any of the message received handlers.

I've put a fix in for this specific bug in the next version, but I suspect your problem is something along the lines of "The app is receiving encrypted messages it can't decrypt". Maybe double-check for trailing whitespace characters, or similar, in the encryption password?

**Comment by jpmens** [comment]
I have double-checked how we load keys:

```
echo "user-pixel3 *supersecretkey*"| ocat --load=keys
```

appears to be okay b/c we chomp `\r` and `\n` at end of line.

**Comment by s256** [comment]
Thanks for the answers. I double checked my PKI setup - as well as with `openssl s_client -connect $servername:port -cert $foo -key $bar -CAfile $fullchain.pem` as well as `openssl verify`. First establishes a proper TLS connection with mutual TLS, the latter confirm that the certs are issued by the intermediate, which itself is coming from my root CA. I read about `libsodium` before. Can you link your fix?  Does this also affect the iOS version?

**Comment by growse** [comment]
Libsodium is what we use to do the symmetric encryption of the messages. Completely unrelated to TLS.

Have you tried the latest version (2.4.4)? I put a change in so that problems encountered decrypting a symmetrically encrypted message don't manifest as a TLS / MQTT error and disconnect.
