### ISSUE TITLE
Repeated geofence leave/return while device stationery

### ISSUE THREAD

**Issue by Mark-VG** [owntracks/android#1134]
* **App build number**: 2.4.3 (24317)
* **Android version**:   11
* **Device**: Samsung Galaxy A02 (SM-A022F/DS) 

Using Owntracks with openHAB (GPS Tracker Binding) for presence detection

OwnTracks keeps sending geofence/region changes even when the device is stationery on a table (being charged or used).

Have set the Inaccurate Locations to 30 m - so inaccurate GPS data should be ignored.

Not sure what else I can do/try to resolve this? Can't seem to find any resolutions on the web.

Any suggestions?

**Comment by growse** [comment]
Do you have a log, or record of location messages that OT is outputting to MQTT/HTTP?

It's possible there's a bug where the inaccurate location filter isn't being applied for region detection, which I can check. But it'd be interesting to see the region change messages alongside the actual location messages that it's sending out (along with the accuracy it thinks it has for each of those locations).

**Comment by Mark-VG** [comment]
Hi Andrew.

Hope this is what you need? Happened just after I git the above message

[Leave and Enter.txt](https://github.com/owntracks/android/files/7632815/Leave.and.Enter.txt)

Thanks for looking

**Comment by growse** [comment]
So it doesn't look like the location moves very far, but it's enough to trigger the region. Is it correct that the lat/lng published as part of the exit transition is out of the region, whereas the lat/lng published as part of the enter transition is in-region?

Also, can you correlate any event that caused this to start happening? New phone, new app version, new phone firmware / Android version, new location, new region?

I've seen this before on some devices (not going to squarely point the finger at Samsung just yet), but the location provided to the `FusedLocationClient` is often more of a "best guess" after being run through a number of clever filters and algorithms. This is especially true on certain devices and in places where the GPS signal isn't particularly strong. This can lead to the device seeming to "walk" around a particular spot, even if it's physically stationary. In an ideal world, each location point supplied to applications should have an appropriate accuracy value so that the actual, real location of the device is somewhere in the circle defined by the lat/lng and the accuracy. However, the world is not always so ideal....

**Comment by Mark-VG** [comment]
Yes, it looks like the location on LEAVE is out of the region - see screen shot.
![Map](https://user-images.githubusercontent.com/84638697/144230924-617f7cc8-a346-4820-8101-3024c1e43631.jpg)

The frequency definitely seems to be worse after getting a new device (with a newer Android version, but this has been an ongoing issue for some time. Previously had a Sony device with same sort of issue.

So am I understanding that this appears to be a device issue? Are you aware of any potential fixes that I could try?

**Comment by Mark-VG** [comment]
Unfortunately the locations, even with the accuracy fall outside the region:

![Map 2](https://user-images.githubusercontent.com/84638697/144362406-d6b9dbe3-c949-4407-bd23-9ffb1d858cac.jpg)

Your idea would have been great otherwise.

I guess I will have to see what my options are with Samsung... Though Google doe snot seem to throw up any similar issues.

**Comment by growse** [comment]
Ah, that's annoying. I've added the change, so try the next release (2.4.4) and see if it makes it any better.
