### ISSUE TITLE
Unable to find some strings to translate on POeditor

### ISSUE THREAD

**Issue by kri164** [owntracks/android#1155]
Hello Andrew,

I cannot find some strings:

Settings-> Theme

1) Always in light theme
2) Always in dark theme
3) Same as device

And what exactly is
Geocoder provider - NONE ?
Is it a value of variable or description, what can be translated?

Thank you

**Comment by growse** [comment]
POEditor doesn't support string-arrays, so updating these unfortunately has to be done via PR. Annoying :(

So that affects:

```
    <string-array name="geocoders">
        <item>None</item>
        <item>Device (Google)</item>
        <item>OpenCage</item>
    </string-array>
    <string-array name="themeLabels">
        <item>Always in light theme</item>
        <item>Always in dark theme</item>
        <item>Same as device</item>
    </string-array>
```

> And what exactly is
> Geocoder provider - NONE ?
> Is it a value of variable or description, what can be translated?

It's an option for the user to select that they don't want any of their locations reverse geocoded. The app just displays the lat/lng instead of resolving it to an address.

**Comment by kri164** [comment]
[owntrack-strings-cs-update.patch.zip](https://github.com/owntracks/android/files/7846741/owntrack-strings-cs-update.patch.zip)

There is a patch file.
