### ISSUE TITLE
Bug: App doesn't request background location permission

### ISSUE THREAD

**Issue by sebastiannielsen** [owntracks/android#1166]
* **App build number**: 2.4.6 (24600)
* **Android version**: 12
* **Device**: Samsung Galaxy S21 Ultra 5G
* **Installation source**: Play

Currently, the app doesn't request background location permission, meaning its unable to work unless its main activity is on top. It should be possible to use background location permission with app.

**Comment by growse** [comment]
It works just fine here for me (and lots of other people) without the main activity being in the foreground.

Rather than getting sidetracked as to what you think the solution is (background location permission doesn't do what you think it does), can you elaborate a bit more on the problem?

* What does "unable to work" mean?
* HTTP or MQTT?
* All monitoring modes, or just some of them?
* Do you see the persistent notification indicating the service is running?
* If you "report location" from the notification, does it send a location message?
* Did you whitelist the app in whatever version of "battery optimization" settings your particular flavour of Android runs?
