### ISSUE TITLE
v2.4.10-beta1 report

### ISSUE THREAD

**Issue by kri164** [owntracks/android#1280]
Hello Andrew,

there are few issues with last beta version:

- string Enable Map rotation is not translated. I cannt find it on POEditor.com
- the second page of Welcome wizard is not scrollable and doesnt display all text
- when opening the section Settings -> Map, it has wrong headline description (Notification instead Map)
- when open Friends and click to some name, it doesnt show friend position on map. It was working in previous versions.
- when export configuration, it reports Export failed eveytime not depend on result of export.

Regards

**Comment by growse** [comment]
Hi!

Thanks for letting me know. Hopefully these are just minor regressions, but I'll take a look at each:

> string Enable Map rotation is not translated. I cannt find it on POEditor.com

Ah, yes, I forgot to sync back up to POEditor after adding some resources. Have now synced. I see some translations have already been updated, so folded them in on d373b8eb

> the second page of Welcome wizard is not scrollable and doesnt display all text

Youch, I should test on smaller screen sizes :) Should now be fixed in 29f7c43c

> when opening the section Settings -> Map, it has wrong headline description (Notification instead Map)

Good spot, fixed in 413b6a2b

> when open Friends and click to some name, it doesnt show friend position on map. It was working in previous versions.

I saw this too, and I think I fixed this already in 0b739fc396c8d373e1eaafa1322f24b63e9feb5e

> when export configuration, it reports Export failed eveytime not depend on result of export.

This has been flaky for a while, it needs some more in-depth love.

I'll cut another beta now. Thanks!

**Comment by kri164** [comment]
Thanks for info.
I will test the next beta too.
Regs
pk



3. září 2022 14:04:18 SELČ, Andrew Rowson ***@***.***> napsal:

**Comment by growse** [comment]
> when export configuration, it reports Export failed eveytime not depend on result of export.

Just an update on this. The problem here is that OT only gets to see a simple "Activity Result Code" from the sharing. When you hit "export", and it pops up a dialog to share with, clicking on an app starts a new Activity. It's sort of up to that application to correctly report the status of being given some data that's been shared with it. 

From testing, for apps which behave "properly" (e.g. Google Drive), any action that results in the file not being saved to Google Drive returns a "Cancelled" message back to OT, which then displays that "failed" message.

Which app are you sharing with? I'll see if I can test with that one explicitly to work out what's going on.

**Comment by kri164** [comment]
Hello Andrew,


I used application Editor (Simple generic text editor) from Bill Farmer 
on F-Droid.

https://f-droid.org/en/packages/org.billthefarmer.editor/


pk

**Comment by growse** [comment]
> This has been flaky for a while, it needs some more in-depth love.

I've dropped the error message, as the "canceled" result is not necessarily an error.

I think with that and #1379, that covers everything here?
