### ISSUE TITLE
0.5.09 over 330 kms

### ISSUE THREAD

**Issue by jpmens** [owntracks/android#131]
I note:

1. many lwt
2. No enter $HOME event because app last reported an hour ago, approx 100 kms from where I now am. :-)

Not sure this is helpful for you, but you may find the odd tidbit in today's log: 

```
{"_type":"location","tst":"1426832465","acc":"18.77","batt":"4","t":"u","tid":"n4"}
{"_type": "lwt", "tst": "1426832433"}
{"_type":"location","tst":"1426838885","acc":"40.05","batt":"36","tid":"n4"}
{"_type":"location","tst":"1426838885","acc":"40.05","batt":"36","tid":"n4"}
{"_type": "lwt", "tst": "1426838721"}
{"_type": "lwt", "tst": "1426839675"}
{"_type": "lwt", "tst": "1426840590"}
{"_type": "lwt", "tst": "1426841101"}
{"_type": "lwt", "tst": "1426842619"}
{"_type": "lwt", "tst": "1426843192"}
{"_type": "lwt", "tst": "1426843645"}
{"_type": "lwt", "tst": "1426844098"}
{"_type": "lwt", "tst": "1426844865"}
{"_type": "lwt", "tst": "1426845881"}
{"_type": "lwt", "tst": "1426846606"}
{"_type": "lwt", "tst": "1426847700"}
{"_type": "lwt", "tst": "1426848301"}
{"_type": "lwt", "tst": "1426851119"}
{"_type": "lwt", "tst": "1426853096"}
{"_type":"location","tst":"1426856520","acc":"38.46","batt":"100","tid":"n4"}
{"_type":"location","tst":"1426857185","acc":"39.0","batt":"99","tid":"n4"}
{"_type":"location","tst":"1426857488","acc":"858.0","batt":"98","tid":"n4"}
{"_type": "lwt", "tst": "1426857035"}
{"_type": "lwt", "tst": "1426860617"}
{"_type":"location","tst":"1426859023","acc":"1252.0","batt":"97","tid":"n4"}
{"_type":"location","tst":"1426860895","acc":"63.0","batt":"96","tid":"n4"}
{"_type": "lwt", "tst": "1426860895"}
{"_type":"location","tst":"1426862229","acc":"10.0","batt":"94","tid":"n4"}
{"_type": "lwt", "tst": "1426863091"}
{"_type":"location","tst":"1426864933","acc":"2558.0","batt":"93","tid":"n4"}
{"_type": "lwt", "tst": "1426864181"}
{"_type": "lwt", "tst": "1426866024"}
{"_type":"location","tst":"1426865290","acc":"2923.0","batt":"92","tid":"n4"}
{"_type": "lwt", "tst": "1426867623"}
{"_type":"location","tst":"1426867743","acc":"10.0","batt":"91","tid":"n4"}
{"_type": "lwt", "tst": "1426868391"}
```

**Comment by binarybucks** [comment]
Re lwt: what keepalive value is set?
Re no updates: I'm slowly convinced that you cannot do reliable location
reporting with the train wreck of Play Services location API. Try rebooting
the device, I'm quite certain that it will work again afterwards.

--
Alexander Rust

On 20 Mar 2015, at 18:17, JP Mens <notifications@github.com> wrote:

I note:

   1. many lwt
   2. No enter $HOME event because app last reported an hour ago, approx
   100 kms from where I now am. :-)

Not sure this is helpful for you, but you may find the odd tidbit in
today's log:

{"_type":"location","tst":"1426832465","acc":"18.77","batt":"4","t":"u","tid":"n4"}
{"_type": "lwt", "tst": "1426832433"}
{"_type":"location","tst":"1426838885","acc":"40.05","batt":"36","tid":"n4"}
{"_type":"location","tst":"1426838885","acc":"40.05","batt":"36","tid":"n4"}
{"_type": "lwt", "tst": "1426838721"}
{"_type": "lwt", "tst": "1426839675"}
{"_type": "lwt", "tst": "1426840590"}
{"_type": "lwt", "tst": "1426841101"}
{"_type": "lwt", "tst": "1426842619"}
{"_type": "lwt", "tst": "1426843192"}
{"_type": "lwt", "tst": "1426843645"}
{"_type": "lwt", "tst": "1426844098"}
{"_type": "lwt", "tst": "1426844865"}
{"_type": "lwt", "tst": "1426845881"}
{"_type": "lwt", "tst": "1426846606"}
{"_type": "lwt", "tst": "1426847700"}
{"_type": "lwt", "tst": "1426848301"}
{"_type": "lwt", "tst": "1426851119"}
{"_type": "lwt", "tst": "1426853096"}
{"_type":"location","tst":"1426856520","acc":"38.46","batt":"100","tid":"n4"}
{"_type":"location","tst":"1426857185","acc":"39.0","batt":"99","tid":"n4"}
{"_type":"location","tst":"1426857488","acc":"858.0","batt":"98","tid":"n4"}
{"_type": "lwt", "tst": "1426857035"}
{"_type": "lwt", "tst": "1426860617"}
{"_type":"location","tst":"1426859023","acc":"1252.0","batt":"97","tid":"n4"}
{"_type":"location","tst":"1426860895","acc":"63.0","batt":"96","tid":"n4"}
{"_type": "lwt", "tst": "1426860895"}
{"_type":"location","tst":"1426862229","acc":"10.0","batt":"94","tid":"n4"}
{"_type": "lwt", "tst": "1426863091"}
{"_type":"location","tst":"1426864933","acc":"2558.0","batt":"93","tid":"n4"}
{"_type": "lwt", "tst": "1426864181"}
{"_type": "lwt", "tst": "1426866024"}
{"_type":"location","tst":"1426865290","acc":"2923.0","batt":"92","tid":"n4"}
{"_type": "lwt", "tst": "1426867623"}
{"_type":"location","tst":"1426867743","acc":"10.0","batt":"91","tid":"n4"}
{"_type": "lwt", "tst": "1426868391"}

—
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/131>.

**Comment by jpmens** [comment]
Keepalive = default (empty, i.e. 3600)

**Comment by jpmens** [comment]
BTW the connection prefs page says `Paremeters` (typo :-)

**Comment by jpmens** [comment]
Switching phone on to look at keepalive pubilshed a message (at $HOME), but no event.

**Comment by binarybucks** [comment]
A recent messages or a queued one? If it's a recent one, the lib is really
broken as the Geofences are generally independent from the normal location
request for reports (even less influence).

--
Alexander Rust

On 20 Mar 2015, at 18:39, JP Mens <notifications@github.com> wrote:

Switching phone on to look at keepalive pubilshed a message (at $HOME), but
no event.

—
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/131#issuecomment-84084028>.

**Comment by jpmens** [comment]
Recent: `tst=1426872967 Fri Mar 20 18:36:07 2015`

**Comment by binarybucks** [comment]
In this case
1. Kill you device with ~~fire~~ a reboot
2. Go to https://code.google.com/p/android/issues/detail?id=57707 and report with your Play Services version that the issue is NOT obsolete

Regarding lwts, I've no idea why the broker considers the connection as terminated even though less than the keepalive interval passed (e.g. between the publish at 1426857488 and the following lwt at 1426857035 we have 453 seconds passed which is << than 3600). 
On the Android side the OS could close the TCP connection when a cell handover appears (7 minutes at 120 km/h is around 14 km which is an entirely possible GSM cell size), but then the broker wouldn't only notice it after 3600 seconds unless the app sends a clean disconnect (which it can't when a handover appears). 

Any ideas? I'll ask ralight if there are any known defects with longer keepalive values.

**Comment by binarybucks** [comment]
I dug a bit in the 3.1.1 spec. Max keepalive us 16bit so 3600 s fits is
valid. The broker expects activity or PINGREQs in 1.5xkeepalive after which
it may terminate the connection. The app sends pings every keepalive
seconds so this should also be fine. However the spec says that  "a Server
is permitted to disconnect a Client that it determines to be inactive or
non-responsive at any time, regardless of the Keep Alive value provided by
that Client.".
I would guess that this is the case. Can you try with a smaller keepalive?
This will use more battery but maybe it convinces the broker that we're
still around.
--
Alexander Rust

On 20 Mar 2015, at 18:45, JP Mens <notifications@github.com> wrote:

Recent: tst=1426872967 Fri Mar 20 18:36:07 2015

—
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/131#issuecomment-84086283>.

**Comment by jpmens** [comment]
Bad news: I enter keepalive (e.g. `300`), but that value isn't saved. When I tap on Parameters again, field is empty with default of 3600 behind it.

**Comment by jpmens** [comment]
I see from the last import I did that keepalive was 60.

I have imported a new config with keepalive=360 and have verified that the broker sees that (even though Parameters doesn't display it)

```
connected from xxx as jpm/nex4 (c1,k360, ujpm).
```

**Comment by jpmens** [comment]
Keepalive setting now works in 0.5.10, thanks.
