### ISSUE TITLE
"Allow OwnTracks the following permissions?" -> "always" missing

### ISSUE THREAD

**Issue by natrius** [owntracks/android#1397]
* **App build number**: 2.4.10 (20410051) OSS
* **Android version**: 10
* **Device**: Xiaomi Mi9
* **Installation source**: F-Droid

Just got "Deny", "Once" and "Allow only while using the app" as possibility. 

Or is this simply a thing i have to live with as i use an Xiaomi phone? :D

**Comment by growse** [comment]
See #1095. TLDR: you shouldn't need it because there's a foreground service running which receives location udpates.

That said, it's coming in the next version, because you need that permission to use the Google Play Services geofencing client. I just need to finish the next version and then do the paperwork with Google to convince them to allow me to publish it.

**Comment by natrius** [comment]
Oh, i missed that. Thanks for your quick answer and explanation! :)
