### ISSUE TITLE
Notifications for Friends arriving and departing Regions

### ISSUE THREAD

**Issue by almulder** [owntracks/android#1580]
First I want to say thanks for making this. I had been using life 360 for a few years but integrations with home automation is being removed and stoped working for many. This is a great replacment. 

Anyways. Something I miss from life 360 was the notifications from friends (Famiky) leaving or entering regions (locations)  I love getting the notification when wife left work so I could get dinner started and done by the time she got home. (She worked random hours)

Keep up the great work and don't be suppried if you start getting alot of new people downloading and using. 

I know it's open source and we can always sideload. But have you thought about charging like $0.99 so you get something back for everything you do. Just a thought. 😀

**Comment by jpmens** [comment]
> Something I miss was the notifications from friends (Family) leaving or entering regions

You don't need to miss them. If you are permitted to see friends (think MQTT ACL for instance), and you're also permitted to see their `"_type": "transition"` publishes, you will receive a notification whenever a friend enter or leaves a particular region.

More on this in our [Booklet](https://owntracks.org/booklet/tech/json/), search for `_type=transition`.

BTW this applies likewise to your own transitions in/out of geofences.

**Comment by ckrey** [comment]
The client apps (Android and iOS) do not need to be configured for send / receive transitions.

As @jpmens pointed out, this works with an MQTT message broker with the appropriate ACL. It forwards all your location and transition messages to your friends and vice versa.

You are using the Hubitat HTTP backend. We have no idea if they implemented forwarding transition messages.

**Comment by troycarpenter** [comment]
I think what confused me coming from Life360 is that with Owntracks, you will be notified of region transitions by default ONLY if that person has defined the region on their device.  If you define regions on your device, you will not be notified if other people transit those regions.  The regions are device specific, and the device will publish when it enters or leaves the region.  Everyone else will be notified since by default they are by default subscribed to those notifications.

So for instance, if your wife defines a Work region on her device, then you should get notified when she enters or exits that region.  But unless you have the same region defined on your device, nobody gets notified if you go in and out of that region.  Regions are not global across all users.

What that means in practice is that you can't define a region on your device that you are interested in others entering or leaving.  That's different than Life360 where when one person creates a region or zone, it applies to everyone.  I asked something similar here: https://github.com/owntracks/talk/issues/176

**Comment by jpmens** [comment]
Closing as answered
