### ISSUE TITLE
certificate handling

### ISSUE THREAD

**Issue by ttyS4** [owntracks/android#276]
Well, I had a problem and as part of doing a proper bug report I researched the issue and realized my own mistake :-)

I still have an issue, but I think instead of a bug it can be regarded as an enhancement request.

I upgraded from the legacy version and was under the impression that it uses the internal CA store to verify the certificate validity. This is not the case. It reads in an external file which is a hassle to get in place if one is without a computer. Browsers try to import it if someone tries to get `myca.crt` and `myca.txt` cant be copy-and-pasted either because they mess up again (and if you load a broken pem file you get weird error messages). Naming it `myca.bin` can help because the browser will download it by default.

Then if I use this file it works without an issue.

The user experience would be better if the internal CA store could be used instead. Also when using an external file there is no guarantee that no one tampered with the file, because there are no security permissions on external files, other apps can modify it. 

![owntracks-cert-error](https://cloud.githubusercontent.com/assets/4060375/10270302/5ef41af8-6aed-11e5-84ef-f9d74aad43c4.png)

**Comment by binarybucks** [comment]
the app uses the internal system certificate store if you do not provide a
custom tls certificate. The later feature is just for those people that
need a custom certificate but don't want a lockscreen password due to an
imported certificate.

In that case, file permissions are the least of your problems anyway.

Could you test if it uses the system keystore? Not much has changed with
that code from the legacy version.

Mit freundlichen Grüßen / With kind regards
Alexander Rust

On 04 Oct 2015, at 23:13, Csillag Tamas <notifications@github.com> wrote:

Well, I had a problem and as part of doing a proper bug report I researched
the issue and realized my own mistake :-)

I still have an issue, but I think instead of a bug it can be regarded as
an enhancement request.

I upgraded from the legacy version and was under the impression that it
uses the internal CA store to verify the certificate validity. This is not
the case. It reads in an external file which is a hassle to get in place if
one is without a computer. Browsers try to import it if someone tries to
get myca.crt and myca.txt cant be copy-and-pasted either because they mess
up again (and if you load a broken pem file you get weird error messages).
Naming it myca.bin can help because the browser will download it by default.

Then if I use this file it works without an issue.

The user experience would be better if the internal CA store could be used
instead. Also when using an external file there is no guarantee that no one
tampered with the file, because there are no security permissions on
external files, other apps can modify it.

[image: owntracks-cert-error]
<https://cloud.githubusercontent.com/assets/4060375/10270302/5ef41af8-6aed-11e5-84ef-f9d74aad43c4.png>

—
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/276>.

**Comment by ttyS4** [comment]
Right, I can confirm it actually uses the internal CA store.
