### ISSUE TITLE
Payload encryption

### ISSUE THREAD

**Issue by jpmens** [owntracks/android#299]
As suggested [here](https://github.com/owntracks/owntracks/issues/7) and as discussed internally.

**Comment by binarybucks** [comment]
Implemented in latest master

**Comment by skorokithakis** [comment]
How can we access this? I don't see it in 5.23. Fantastic job with own

**Comment by jpmens** [comment]
Thanks for the friendly comment. Payload encryption will be in the next Android version.

**Comment by skorokithakis** [comment]
Great, thank you. Do you know when that will be released?

**Comment by jpmens** [comment]
Yes, the exact date is "when it's ready"! ;-)
As with all things Open Source, that's the only response I can give you.
We are currently beta-testing, so it should be "quite soon".

**Comment by skorokithakis** [comment]
Haha, OK. Can I request that you update the build instructions? I tried to build from source but the keys were in a different place and it also needed some other keys.

**Comment by binarybucks** [comment]
Please submit a pull request for that. I'm not sure what you're referring
to but I'm happy to update the instructions.

Mit freundlichen Grüßen / With kind regards
Alexander Rust

On 19 Mar 2016, at 09:43, Stavros Korokithakis <notifications@github.com>
wrote:

Haha, OK. Can I request that you update the build instructions? I tried to
build from source but the keys were in a different place and it also needed
some other keys.

—
You are receiving this because you modified the open/close state.
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/299#issuecomment-198669172>

**Comment by skorokithakis** [comment]
I'm afraid I can't submit a pull request, as I didn't manage to build it in the end. The instructions for building in the readme aren't working. Gradle sync first gave me an error, the API keys were in a different file and there are other map keys required as well.

**Comment by binarybucks** [comment]
If you tell me which gradle error you encountered I might actually do
something against it

Mit freundlichen Grüßen / With kind regards
Alexander Rust

On 19 Mar 2016, at 14:11, Stavros Korokithakis <notifications@github.com>
wrote:

I'm afraid I can't submit a pull request, as I didn't manage to build it in
the end. The instructions for building in the readme aren't working. Gradle
sync first gave me an error, the API keys were in a different file and
there are other map keys required as well.

—
You are receiving this because you modified the open/close state.
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/299#issuecomment-198701063>

**Comment by skorokithakis** [comment]
In the end all that was needed was a manual update to the latest build tools, as the automatic update was breaking. Just the key file location needs to be changed, and some detail about what the mapbox API key is and how to get it. The new release is looking great, I can't wait to run it!

**Comment by skorokithakis** [comment]
By the way, @jpmens, is there a beta channel I can join to get in the beta test?
