### ISSUE TITLE
Use onLocationChanged to avoid running in the background?

### ISSUE THREAD

**Issue by skorokithakis** [owntracks/android#340]
Would it be possible to use [onLocationChanged](https://developer.android.com/training/location/receive-location-updates.html) to connect to the server and send the message, and avoid running a background service at all times? The app could also be configured to buffer N updates and send them all together at a later time.

**Comment by binarybucks** [comment]
we're already using onLocationChanged. This and maintaining a broker connection are two different things. The background service itself is required to receive the location updates of the device. 
The broker connection is a design decision. Getting rid of it kinf of defeats the purpose of the MQTT protocol. In the next versions HTTP support will be added which allows for stateless reports.

**Comment by skorokithakis** [comment]
Sorry, which location updates is it required for? I'm unclear on whether I can disable the background service and have the app report properly or not.

**Comment by binarybucks** [comment]
The background service registers as a receiver for changes in the device location. 
If you disable it (e.g. by disabling the ongoing notification) there will be nothing that gets notified of updates because the app isn't running anymore. Hence, you cannot disable the background service.

**Comment by skorokithakis** [comment]
Ah, I see what you mean, I thought the app will be woken up long enough to report the location. Will the HTTP support mean that the service can be stopped, or will a service always be required for reporting?

**Comment by binarybucks** [comment]
The service will always be required. 
If android detects a location change, it cannot magically make the new location data appear on the broker. It allows other apps to register for location changes by registering the onLocationChanged callback. 

Now, if you stop the background service, there isn't anything the new locaton can be delivered to because once an app is stopped, all callbacks are removed (there are exceptions to this, but that's how it currently works for OwnTracks). 

So no background service, no background location updates. HTTP mode will not establish a persistent TCP connection but still require a background service for background location updates.

**Comment by skorokithakis** [comment]
I see, thanks.
