### ISSUE TITLE
Expose "reportLocation" functionality in-app

### ISSUE THREAD

**Issue by hoalex** [owntracks/android#342]
First of all, great job on the new Android client! :+1: I'm especially happy over the new iBeacons functionality which works like a charm for me :-)

I've got one small feature request, which I guess should not be too complicated to implement. I think it would be great to have an option inside the app to send a ```reportLocation``` command to a client in the friends list. Currently, this is only possible by manually passing the corresponding JSON to the MQTT broker -- which is kind of complicated when you're on the move.

One possible scenario for this would be to get a location update from a moving client when it is in ```significant changes``` mode, but did not yet reach the threshold neccessary for causing a location update to the broker.

I think a possible place to position this function could be in the overflow menu that appears when selecting a person on the map.

What do you think? :)

Regards,
Alex

**Comment by binarybucks** [comment]
We've currently opted to remove the reportLocation from the apps for several reasons
1) due to the nature of iOS (and soon Android) background services, the app does not maintain a connection, so it can take quite a long time until the command reaches the target device
2) with HTTP mode, this is even more of a problem

Hence, the apps do support it when they receive a command, but the nature of both operating systems doesn't make it as instantaneous as it would be required for direct interaction with a user. 

Besides that, you're of course right with the usage and placement of the functionality. We just thought that it might be confusing for an uninvolved user.
