### ISSUE TITLE
ToLowerCase()

### ISSUE THREAD

**Issue by jpmens** [owntracks/android#345]
As reported here https://mobile.twitter.com/stephanepechard/status/713790102208700416 (screenshots in that thread)

```
03-26 18:42:41.261  3160  7466 E ServiceBroker: MqttException (0) - java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
03-26 18:42:41.261  3160  7466 W System.err: MqttException (0) - java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
03-26 18:42:41.261  3160  7466 W System.err: 	at org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
03-26 18:42:41.261  3160  7466 W System.err: 	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:633)
03-26 18:42:41.261  3160  7466 W System.err: 	at java.lang.Thread.run(Thread.java:818)
03-26 18:42:41.261  3160  7466 W System.err: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String java.lang.String.toLowerCase()' on a null object reference
03-26 18:42:41.261  3160  7466 W System.err: 	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.receiveHandshakeResponse(WebSocketHandshake.java:106)
03-26 18:42:41.261  3160  7466 W System.err: 	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.execute(WebSocketHandshake.java:66)
03-26 18:42:41.261  3160  7466 W System.err: 	at org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketNetworkModule.start(WebSocketNetworkModule.java:77)
03-26 18:42:41.261  3160  7466 W System.err: 	at org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:619)
03-26 18:42:41.261  3160  7466 W System.err: 	... 1 more
```

**Comment by binarybucks** [comment]
Great, thanks for the stacktrace. Makes it much easier to fix the issue.

Can I assume that you tried to connect via websockets?

Mit freundlichen Grüßen / With kind regards
Alexander Rust

On 26 Mar 2016, at 20:10, JP Mens <notifications@github.com> wrote:

As reported here
https://mobile.twitter.com/stephanepechard/status/713790102208700416
(screenshots in that thread)

03-26 18:42:41.261  3160  7466 E ServiceBroker: MqttException (0) -
java.lang.NullPointerException: Attempt to invoke virtual method
'java.lang.String java.lang.String.toLowerCase()' on a null object
reference
03-26 18:42:41.261  3160  7466 W System.err: MqttException (0) -
java.lang.NullPointerException: Attempt to invoke virtual method
'java.lang.String java.lang.String.toLowerCase()' on a null object
reference
03-26 18:42:41.261  3160  7466 W System.err:    at
org.eclipse.paho.client.mqttv3.internal.ExceptionHelper.createMqttException(ExceptionHelper.java:38)
03-26 18:42:41.261  3160  7466 W System.err:    at
org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:633)
03-26 18:42:41.261  3160  7466 W System.err:    at
java.lang.Thread.run(Thread.java:818)
03-26 18:42:41.261  3160  7466 W System.err: Caused by:
java.lang.NullPointerException: Attempt to invoke virtual method
'java.lang.String java.lang.String.toLowerCase()' on a null object
reference
03-26 18:42:41.261  3160  7466 W System.err:    at
org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.receiveHandshakeResponse(WebSocketHandshake.java:106)
03-26 18:42:41.261  3160  7466 W System.err:    at
org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketHandshake.execute(WebSocketHandshake.java:66)
03-26 18:42:41.261  3160  7466 W System.err:    at
org.eclipse.paho.client.mqttv3.internal.websocket.WebSocketNetworkModule.start(WebSocketNetworkModule.java:77)
03-26 18:42:41.261  3160  7466 W System.err:    at
org.eclipse.paho.client.mqttv3.internal.ClientComms$ConnectBG.run(ClientComms.java:619)
03-26 18:42:41.261  3160  7466 W System.err:    ... 1 more

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/345>

**Comment by stephanepechard** [comment]
Thanks for creating the issue. 
Effectively, I try to connect through Websockets on my personal server (Debian Jessie / Nginx 1.8.1 as a proxy). 
I use Let's Encrypt certificate on a subdomain to reach mosquitto 1.3.4, without TLS at the moment.

**Comment by binarybucks** [comment]
@stephanepechard this seems to be a Paho bug. Could you send your broker address to support@owntracks.org so I can try to replicate it in order to file a Paho issue?

**Comment by stephanepechard** [comment]
Done

**Comment by heytcass** [comment]
I am also having the same issue. Trying to connect with web sockets using LetsEncrypt to a subdomain through nginx. Was a solution found at all?

**Comment by binarybucks** [comment]
No, it is an issue in the Paho Websocket function that we cannot fix.

**Comment by alanbo80** [comment]
So, as it seems to be Paho bug, we cannot look forward to get owntracks work with a private MQTT Broker using WebSockets ?
Thank you.

**Comment by binarybucks** [comment]
Websocket connections work fine, except sometimes they don't. In that case a future Pahl version might fix it. 
Judging from the speed of development, it can only be a few more years.

**Comment by alanbo80** [comment]
Hi Alex,

thanks for your quick response. WS work fine ? I forgot to mention i also try to use TLS && Certificates.
I've just setup a WS/TLS Connection and i ran exactly into the error mentioned above. Null-Point-Exception. As i sniffed the incoming traffic at my firewall and do see no traffic related to mqtt i guess it's a client issue. So i guessed, according to a post January '17 that maybe i was hit by the same issue and the issue is not fixed yet.

A few more years ? Dooh, i hoped to get it done this week :-)

Thanks for your help.

Regards,
Alex

**Comment by jeremiasdsa** [comment]
I'm getting the same log error. 
Any workaround ?
