### ISSUE TITLE
Bluetooth Beacon functionality can cause battery drain

### ISSUE THREAD

**Issue by ertanden** [owntracks/android#347]
I don't have hard evidence but it looks like OwnTracks causes huge battery drain on my Nexus 6P with Android 6.0.1 stock. 

The problem probably originates from a bug in Android stock ROM, but it looks to be related to BLE and thus the beacon code in OwnTracks.

[related Android issue 1](https://code.google.com/p/android/issues/detail?can=2&start=0&num=100&q=&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened&groupby=&sort=&id=87778
)
[related Android issue 1](https://code.google.com/p/android/issues/detail?id=198180)

For the time being, it prevents me from using OwnTracks. So I wonder if it's possible to add a preference to completely disable the Bluetooth Beacon functionality since I don't have a use case for it.

**Comment by binarybucks** [comment]
Mhh, could you not just remove all regions that use beacons? 
Or is it a more general issue that is caused even tough no regions are monitored?

**Comment by ertanden** [comment]
I don't have any regions configured. Is it possible that the beacon code is initialized regardless of any regions defined?

**Comment by binarybucks** [comment]
yes it is. 
I'll add a config attribute to disable it completely. 
Could you subscribe to beta releases at https://play.google.com/apps/testing/org.owntracks.android please? 
I'll submit a new build shortly. Please let me know if it fixes your problem.

**Comment by ertanden** [comment]
Great, I subscribed to beta releases. Thanks!

**Comment by binarybucks** [comment]
Whops, didn't mean to close this. 
Beta is on the way and should arrive as an update shortly. 
It now just enables any BLE interaction if you setup a Region with a beacon UUID. 
Additionally, you can import a configuration with the following attribute 
``` {
    "_type": "configuration",
   "beaconMode": XXX
}
```
where x can have the following values 
0  => normal Bluetooth mode that enables scanning when regions with UUID are defined
1 => Same as 0 but uses legacy beacon scanning instead of Android 6 scanning. Has no effect on devices not running Android < 6.x 
2 => hard disable any Bluetooth functions even if regions with UUID are defined

**Comment by ertanden** [comment]
Installed the beta. Will report tomorrow if everything is ok.

**Comment by ertanden** [comment]
Fix looks good. :+1:
