### ISSUE TITLE
Can not insert a negative value for radius

### ISSUE THREAD

**Issue by travisghansen** [owntracks/android#348]
For iBeacons:

```Setting the radius to a negative value (e.g. -1), the app will update the location coordinates of the waypoint on each enter/leave event. This update will be transmitted to the broker when the share option is on and will be reflected on your map screen. You may use this to keep track of moveable items as luggage or your car.```

However in the android interface when hitting the ```-``` sign on the on screen keyboard nothing happens.

**Comment by binarybucks** [comment]
This is not supported on Android.
@jpmens please update the the docs accordingly.

**Comment by travisghansen** [comment]
@binarybucks Is there an underlying reason this isn't supported on Android?

**Comment by binarybucks** [comment]
Yes, it would need quite some rewrite of the beacon code. 
I'll flag this as future and reopen it.

**Comment by jpmens** [comment]
Booklet updated

**Comment by travisghansen** [comment]
@binarybucks Awesome, thanks!

**Comment by balloob** [comment]
Does this mean that the feature is implemented or that it is no longer considered to be implemented?

**Comment by binarybucks** [comment]
Neither. It will just not be implemented in the near future

Mit freundlichen Grüßen / With kind regards
Alexander Rust

On 17 Jun 2016, at 18:06, Paulus Schoutsen <notifications@github.com> wrote:

Does this mean that the feature is implemented or that it is no longer
considered to be implemented?

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/owntracks/android/issues/348#issuecomment-226811049>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAvwFJ0Zujj59pAQsdx6oztmX1i-QF97ks5qMsYUgaJpZM4H58Bc>
.
