### ISSUE TITLE
HTTP(S) support?

### ISSUE THREAD

**Issue by mnutt** [owntracks/android#356]
I saw a changelog item a little while back about adding underlying support for HTTP. I'm writing instructions for connecting devices to Owntracks, and was just wondering if HTTP support is imminent and I should wait for that. Thanks!

**Comment by jpmens** [comment]
It is imminent; just a wee bit of patience please. As a matter of curiosity, what kind of instructions / whom for?

**Comment by binarybucks** [comment]
I'm currently working on it but it will be another week or two until we
have tested it

On 07 Apr 2016, at 21:47, Michael Nutt <notifications@github.com> wrote:

I saw a changelog item a little while back about adding underlying support
for HTTP. I'm writing instructions for connecting devices to Owntracks, and
was just wondering if HTTP support is imminent and I should wait for that.
Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/356>

**Comment by mnutt** [comment]
No problem, thanks and no rush. I packaged OwnTracks to run in Sandstorm but it only supports the http api. I'll update the instructions to say that it's iOS client only for now and change them when http support lands.

**Comment by saket424** [comment]
Is http mode supported in owntracks for Android now ?

**Comment by binarybucks** [comment]
no
