### ISSUE TITLE
No info panel for friend

### ISSUE THREAD

**Issue by joshproehl** [owntracks/android#362]
It seems that the info panel for users has disappeared, making it difficult to tell how stale a friend's last position is.

I attempted to debug this issue and found that I was running version 0.6.14 (from the Play Store), however 0.6.11 is the last version I see in the repo, so I'm not sure if this change was intentional or accidental.

**Comment by binarybucks** [comment]
6.14 is the latest Play Store version. I've somehow misplaced the APk for
it so it is not on GitHub.

By bottom panel you mean what? The thing that appears when you click a
contact marker on the map or a friend in the list?

Which Android version are you using. The info panel is powered by the
Google support library which has quite some bugs and is not ad backwards
compatible as it advertises.

On 18 Apr 2016, at 20:51, Josh Proehl <notifications@github.com> wrote:

It seems that the info panel for users has disappeared, making it difficult
to tell how stale a friend's last position is.

I attempted to debug this issue and found that I was running version 0.6.14
(from the Play Store), however 0.6.11 is the last version I see in the
repo, so I'm not sure if this change was intentional or accidental.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/362>

**Comment by joshproehl** [comment]
Current operating system is Android 6. (MotoX Pure 2015).
A little further testing revealed that this problem was likely a combination of user error and user misunderstanding. It used to be that while viewing the map you could long-press on the user info bar at the bottom of the screen and the info pane would pop up. Apparently now a swipe-up motion is required.  
Side note: I do not appear to have "center" or "follow" options on the info pane menu.

The reason I say "probably" user error is that I could swear I remembered being able to get the user info pane via the friends list view, not the map view. That may just be a false memory though. :-)
(The desired feature is quick access to how stale the displayed address is.)

My apologies for the invalid report, I feel suitably silly.

**Comment by binarybucks** [comment]
No problem, I'm glad it works now.
Currently you cannot access the details from the list without going back to
the map. Now that you explain the use case I might add it back.

It currently works as follows:
Taping a friend from the list centers him on the map and brings up the
sheet with name and location. Pulling that up shows further details.

Tapping a marker also brings up the details but doesn't center it to quick
check other markets on the map.

Long pressing the sheet of a selected contact (the part with name and
location) centers and follows the contact until you tap another marker or
the map.

On 18 Apr 2016, at 22:16, Josh Proehl <notifications@github.com> wrote:

Current operating system is Android 6. (MotoX Pure 2015).
A little further testing revealed that this problem was likely a
combination of user error and user misunderstanding. It used to be that
while viewing the map you could long-press on the user info bar at the
bottom of the screen and the info pane would pop up. Apparently now a
swipe-up motion is required.

Side note: I do not appear to have "center" or "follow" options on the info
pane menu.

The reason I say "probably" user error is that I could swear I remembered
being able to get the user info pane via the friends list view, not the map
view. That may just be a false memory though. :-)
(The desired feature is quick access to how stale the displayed address is.)

My apologies for the invalid report, I feel suitably silly.

—
You are receiving this because you commented.
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/362#issuecomment-211556834>
