### ISSUE TITLE
Numeric keyboard missing . and -

### ISSUE THREAD

**Issue by johnjore** [owntracks/android#364]
Hi!

On a Samsung A5100, Android 5.1.1, the keyboard when entering GPS coordinates is missing - and . 
See screenshot for details?

Also, if internal sdcard is missing / not available, app will crash after going through the 4? step intro and trying to launch GUI. (On Android 6.0.1 / Samsung S2 i9100) Let me know if this is a bug and a separate issue needs to be created?

Both seen with version 0.6.14.

JJ

<img width="270" alt="screenshot_2016-04-20-20-09-10" src="https://cloud.githubusercontent.com/assets/12951842/14687381/24db5216-0735-11e6-9468-172b63e42546.png">

**Comment by binarybucks** [comment]
The keyboard is a Samsung issue.
Works fine with the stock 4,5 and 6 keyboard.

Please open a separate issue regarding the crash. Probably google Maps
trying to cache things. Please submit a crash report and post the time and
date at which you submitted it so I can locate it.

On 20 Apr 2016, at 21:18, johnjore <notifications@github.com> wrote:

Hi!

On a Samsung A5100, Android 5.1.1, the keyboard when entering GPS
coordinates is missing - and .
See screenshot for details?

Also, if internal sdcard is missing / not available, app will crash after
going through the 4? step intro and trying to launch GUI. (On Android 6.0.1
/ Samsung S2 i9100) Let me know if this is a bug and a separate issue needs
to be created?

Both seen with version 0.6.14.

JJ

[image: screenshot_2016-04-20-20-09-10]
<https://cloud.githubusercontent.com/assets/12951842/14687207/31b5fd98-0734-11e6-9fb3-25aa80b7696a.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/364>

**Comment by binarybucks** [comment]
Also, minus and dot only work were they make sense for a float number (-
not at the end, dot not at the end or beginning and only one)

On 20 Apr 2016, at 21:18, johnjore <notifications@github.com> wrote:

Hi!

On a Samsung A5100, Android 5.1.1, the keyboard when entering GPS
coordinates is missing - and .
See screenshot for details?

Also, if internal sdcard is missing / not available, app will crash after
going through the 4? step intro and trying to launch GUI. (On Android 6.0.1
/ Samsung S2 i9100) Let me know if this is a bug and a separate issue needs
to be created?

Both seen with version 0.6.14.

JJ

[image: screenshot_2016-04-20-20-09-10]
<https://cloud.githubusercontent.com/assets/12951842/14687207/31b5fd98-0734-11e6-9fb3-25aa80b7696a.png>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/364>

**Comment by johnjore** [comment]
Hi and yes that does make sense… Samsung keyboard is pretty fixed in its layout and does not adjust itself to where on the line one tries to enter values…

If issue is with Samsung then I guess issue can be closed. However, the keyboard RSA SecurID uses allows symbols, as per the attachement?

Not sure if its possible to let user choose a different keyboard layout?

JJ

**Comment by johnjore** [comment]
As an FYI, when setting the port for the broker, the "correct" keyboard shows up (same keyboard as RSA uses).

Maybe Samsung swapped things around a bit, as I can only enter numbers when I need . and -, and I can enter - and . when I only need  numbers for the port...

JJ

**Comment by CloCkWeRX** [comment]
Any chance this is a regression related to #57 ?

**Comment by CloCkWeRX** [comment]
I think it was https://github.com/owntracks/android/commit/b7a2bd9eb47108fdffca38b5268a5732955341e5#diff-7891498f343c4a5471d58c1a7cead6b7R79 that caused the regression

**Comment by binarybucks** [comment]
Probably, reverted it to the numberSigned only. I'm not sure why I changed it now.
