### ISSUE TITLE
Location icons not updating after switching to/from wifi/3g

### ISSUE THREAD

**Issue by johnjore** [owntracks/android#367]
Hi!

I run mosquitto on my internal network, with hole in the firewall to reach it from "the outside". Its also configured with split DNS so it works on both internal wifi and external 3/4g using the same hostname and port number.

After switching between wifi/3g, the friends icons on the map do not update. If I force close owntracks or reboot the phone, map updates again work. I can see owntracks is reporting the new location data to the broker as I've configured OpenHAB to also report on the location. Its just the icons on the map that don't update.

Happened twice, both when going from wifi to 3g and back again. I have a few screenshots, but not keen on posting them here as they have my address on them. If you want  them, let me know how I can securely get them to you.

Note: I did not turn wifi/3g on/off, I just left / arrived at the house and let the phone do its thing. Not sure if this makes any difference?

Android 5.1.1 / owntracks 0.6.14.

JJ

**Comment by jpmens** [comment]
When you say _Icons on the map do not update_, I assume you mean the _position_ of the icons, right?

That would mean that messages aren't arriving at your device, which is possibly/probably due to connection to the broker.

As you say you have split DNS: what is the TTL on the DNS records? If it's, say, 3600, that would mean that even if the phone is disconnected, when it attempts to reconnect within the hour it would in fact be trying to reache the wrong address.

**Comment by johnjore** [comment]
Hi and no, its not just the position of the icons, but the data behind it, like the time stamp.

and no, its not the TTL: 
1) force stopping Owntracks and starting it again "fixed" the issue
2) Nothing in the owntracks queue and it was in connected state
3) OpenHAB was seeing the new messages while I was walking around. 

Reasons 1 could be a fluke and the TTL timed out exactly as owntracks was restarted, reason 3 is pretty solid. I believe, I could be wrong, but android flushes its DNS cache when it flips to a different data carrier (wifi/3g) etc. I dont have a TTL issue with any other services when I leave the house, including email. I've also tested this by turning off wifi and seeing that Owntracks changes back to "connected" almost instantly. However, in this scenario, the icons dont actually move so didn't realize there was a problem until I went for a walk.

JJ

**Comment by binarybucks** [comment]
If you open the app again and publish a new location, does the icon update?
The currently available version doesn't update icons to the received
locations when you reopen the app. The next version fixes this. So if the
locations arrive in the background it should work soon.

Mit freundlichen Grüßen / With kind regards
Alexander Rust

On 23 Apr 2016, at 14:48, johnjore <notifications@github.com> wrote:

Hi and no, its not just the position of the icons, but the data behind it,
like the time stamp.

and no, its not the TTL:
1) force stopping Owntracks and starting it again "fixed" the issue
2) Nothing in the owntracks queue and it was in connected state
3) OpenHAB was seeing the new messages while I was walking around.

Reasons 1 could be a fluke and the TTL timed out exactly as owntracks was
restarted, reason 3 is pretty solid. I believe, I could be wrong, but
android flushes its DNS cache when it flips to a different data carrier
(wifi/3g) etc. I dont have a TTL issue with any other services when I leave
the house, including email. I've also tested this by turning off wifi and
seeing that Owntracks changes back to "connected" almost instantly.
However, in this scenario, the icons dont actually move so didn't realize
there was a problem until I went for a walk.

JJ

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/owntracks/android/issues/367#issuecomment-213735115>

**Comment by johnjore** [comment]
Hm... If i force restart the app after switching from wifi to 3g, the map icons do move around on my screen?!? I tried different ways; leaving app in foreground, changing foreground app, and swithing back etc; icon still moved around. 

Here is a sample of the data. From the timestamps, its now been 5h since switching from 3g to wifi, but owntracks still thinks the last "checkin" happened 5h ago.
<img width="270" alt="1" src="https://cloud.githubusercontent.com/assets/12951842/14766786/493da678-0a0e-11e6-8690-1fbcbb8166b9.png">
 
JJ

**Comment by jpmens** [comment]
I cannot reproduce this at all, either with MQTT nor with (alpha) HTTP mode; I tried both, each during 50kms of pretty fast driving; no issues at all.

@johnjore Can we please see the Mosquitto ACL for your user? Not the password file, mind you, just the ACL entry. Please don't obfuscate: if you don't want to divulge topic names send it via e-mail to support@owntracks.org

**Comment by johnjore** [comment]
Hi and email sent.

**Comment by jpmens** [comment]
I was indeed also switching providers.

Thanks for the ACL file. I'll admit I was hoping to find a typo; No typo. OTOH, the typo would have obviously been provider independent, so a moot point; sorry.

**Comment by johnjore** [comment]
1) One more thing to check is the "App started" time in status. It should be before the switch to a new data provider.

2) Not sure what your setup looks like, but was it the same server / ip combination when switching dataprovider? I.e, is the App caching something it shouldn't, and its only reset at startup? Sortof like a variation of TTL?

**Comment by lsowen** [comment]
I'm having a potentially related issue.  I only have one "friend", and it appears that the icon indicating the friend on the map is not always synced to the proper position.  This is most evident when selecting the friend from the friends list, the map centers on the correct point (but with the icon still located at a stale position).  I can usually get the icon to snap to the proper location by:

1. Selecting the friend from the friend list
2. Panning the map to the old location
3. Then clicking on the friend icon which is displayed in the wrong location

I float between wifi w/ vpn, 3g w/ vpn, 3g w/o vpn, wifi w/o vpn, so it may or may not be related to the network transitioning.  Any additional information I can provide which might be useful?

**Comment by binarybucks** [comment]
Map code has been rewritten completely, please reopen if it occurs again.

**Comment by Csepi** [comment]
Dear everyone. It seems, I have this kind of problem now. 
Owntracks tracking my device (in backgroung) when on 3G, but as soon as I arrive somewhere where WIFI available and connected, it doesn't update my location. I have to open Owntracks to update the location again.

Does anyone have the same problem?

Best: Peter

**Comment by binarybucks** [comment]
Please see if the latest 2.1.0 beta improves things for you.

**Comment by Csepi** [comment]
Hi!
Today I joined the beta program to try it, but still it doesn't work - cant change from 3G to Wifi.

Best: Peter

**Comment by binarybucks** [comment]
Hi @Csepi 
just to clarify some things: 
1) Which Android version and device are you using
2) What mode are you using (signifficant location mode, etc). 
3) What‘s your setting for locator displacement and interval
4) You‘re saying that once you switch from 3G to Wifi, Owntracks no longer publishes a location. Is this for all Wifi networks or just a specific one? 
5) When you open Owntracks again and it publishes the location, what happens when you leave the Wifi network? Does the app continue to send updates? 
6) When the app is no longer sending updates when on Wifi, what happens when you hit the „report“ button on the notification?

**Comment by Csepi** [comment]
Hi! First: thank you for helping me!

- Which Android version and device are you using
-- Android 7.0; Homtom (HT50)
- What mode are you using (signifficant location mode, etc).
-- Significant changes mode; Phone: high accuracy
-- after I changed the mode, my location was updated. (Maybe this is the problem? If I don't move? it won't update anymore?)
- What‘s your setting for locator displacement and interval
-- locator displacement: 500 (maybe it's too high? )
-- interval: 90
- You‘re saying that once you switch from 3G to Wifi, Owntracks no longer publishes a location. Is this for all Wifi networks or just a specific one?
-- as I reviewed this is for home and work wifi, I didn't test it furthermore.
- When you open Owntracks again and it publishes the location, what happens when you leave the Wifi network? Does the app continue to send updates?
-- after update 2.1 beta, it doesn't update my location even if I open Owntracks (or restart Owntracks) on wifi. 
-- After I move out of Wifi range, it starts sending updates again.
- When the app is no longer sending updates when on Wifi, what happens when you hit the „report“ button on the notification?
--  it sends the 'old' location to CloudMQTT.

I hope my answers were precise enough :) 
And thank you again!!!

Best: Peter

**Comment by Csepi** [comment]
Hi binarybucs,

Thanks for the explonation, sorry for the late response.

I was on holiday and I tried different settings (also the ping and the different modes)

I found 'Quiet monitoring' is one of the best option, it always update don't care about wifi or mobile line, but... but somehow sometimes (random) it drops me to an older location with low accuracy (~10m) - even if I stay at the same place all the time. After a few minutes it drops 'me' back to home.
![image](https://user-images.githubusercontent.com/5657076/48769098-15962100-ecbb-11e8-887a-7fdda00e019f.png)
I have a bad feeling, that my mobile gps gone wrong, not Owntrack.
I also tried all of the modes, but I found this monitoring is the most useful... 

Thanks for the update anyway, I keep testing :)

If you have further thoughts, please don't hesitate to contact me :)

Best: Peter
