### ISSUE TITLE
Many disconnects, no automatic reconnects

### ISSUE THREAD

**Issue by jostick** [owntracks/android#375]
Somehow Owntracks (0.6.14) has serious problems maintaining a connection to my local Mosquitto server on my Moto X 2014 (2nd gen). If a force a reconnect, it connects successfully sends a few messages and disconnects again after some seconds. The server log look like:
> 1463830228: New connection from 188.194.214.128 on port 8883.
1463830228: New client connected from 188.194.214.128 as m2s/jostick.moto_x (c0, k3600, um2s).
1463830228: Sending CONNACK to m2s/jostick.moto_x (0)
1463830228: Sending PUBREC to m2s/jostick.moto_x (Mid: 418)
1463830228: Sending PUBLISH to m2s/jostick.moto_x (d1, q1, r1, m3377, 'owntracks/jostick/moto_x_2014', ... (113 bytes))
1463830228: Sending PUBLISH to m2s/jostick.moto_x (d1, q1, r1, m3378, 'owntracks/m2s/jostick.moto_x', ... (101 bytes))
1463830228: Sending PUBLISH to m2s/jostick.moto_x (d1, q1, r1, m3379, 'owntracks/jostick/moto_x_2014', ... (113 bytes))
1463830228: Sending PUBLISH to m2s/jostick.moto_x (d1, q1, r1, m3380, 'owntracks/m2s/jostick.moto_x', ... (101 bytes))
1463830228: Sending PUBLISH to m2s/jostick.moto_x (d1, q1, r1, m3381, 'owntracks/jostick/moto_x_2014', ... (113 bytes))
1463830228: Sending PUBLISH to m2s/jostick.moto_x (d1, q1, r1, m3382, 'owntracks/m2s/jostick.moto_x', ... (101 bytes))
1463830228: Sending PUBLISH to m2s/jostick.moto_x (d1, q1, r1, m3383, 'owntracks/jostick/moto_x_2014', ... (113 bytes))
1463830228: Sending PUBLISH to m2s/jostick.moto_x (d1, q1, r1, m3384, 'owntracks/m2s/jostick.moto_x', ... (101 bytes))
1463830228: Sending PUBLISH to m2s/jostick.moto_x (d0, q0, r0, m0, 'owntracks/m2s/jostick.moto_x', ... (32 bytes))
1463830228: Socket error on client m2s/jostick.moto_x, disconnecting.

In this case the disconnect was within 1 seconds. Sometimes it lasts several seconds. Owntracks seems to give up reconnecting on its own regularly.  I have other applications connected to the Mosquitto server. They don't seem to have any issues. 

Am I the only person seeing this? Can I help debugging it?

**Comment by kvoit** [comment]
I second the problem with unreliable connections. In my case, Owncloud apparently gives up reconnecting when it has trouble to resolve the hostname. In my case, such errors occur regularly when transitioning between wifi and mobile and always breaks tracking until I notice the error.
It should be easily solvable with regular reconnection attempts.

**Comment by awrede** [comment]
I also experience reconnect failures. For example,  when the WiFi network the owntrack phone I'd connected to looses Internet connectivity for a while,  owntracks almost never manages to reconnect once connectivity to the Internet is restored.

**Comment by binarybucks** [comment]
I've identified an issue with the reconnect code. Apparently a loss of network connection doesn't kill the socket reliably in some Android versions. 

I'm now testing a fix for this. Until it is available, you can try to lower the keepalive interval by importing a configuration file with the following content. 
```
{
    "_type": "configuration",
    "keepalive": 60
}
```

This will lower the MQTT keepalive value to 60 seconds. Thus the app will notice a disconnect after 60 seconds (+30s backup time). The downside to this fix is that the phone will wakeup every 60 seconds.

**Comment by kvoit** [comment]
I already have my keepalive at 300s (because else there is now way for other to know if I am just gone or in the same place, I don't think the hour is a good choice), and after that time, the connection is not restored.

As I said, Owntracks DOES notice that it is not connected in my case. It tells me it could not resolve the MQTT server. It just doesn't retry. Manually retrying works immediately.

**Comment by jostick** [comment]
I feel there are several different issues discussed in this ticket. My original problem was:
1. Disconnects all the time (after a few seconds). It did work reliably some time ago.
2. Owntracks notices that it is disconnected but stops reconnecting. 

But I think reducing the keepalive is a good idea. It shouldn't use too much battery. And big thanks for fixing the reconnect code.

**Comment by binarybucks** [comment]
Fixed in master (hopefully)

**Comment by jostick** [comment]
Nice. Thanks a lot!

**Comment by kvoit** [comment]
Could you tell what you fixed? As jostick said, there are multiple issues discussed here which ll fit under that headline.

**Comment by binarybucks** [comment]
Much of the background service has been rewritten as there were multiple
things that didn't work in specific situations. E.g. the background timer
that triggers reconnect attempts wasn't registered correctly.

The automatic detection of network changes was removed completely because
it didn't work, causes in unnecessary device wakeups and is also not
supported in Android 7.

Depending on the keepalive value, it also took some time to register a
timeout (1h) by default. That issue cannot be fixed directly but should not
occur that often in the new version. In areas with very bad reception you
can try to play with the keepalive value or use the new HTTP mode which
doesn't have this problem.

In general the new code should connect correctly after some time. It also
supports the new Android 7 power saving mode in which no background data
connection is allowed. Publishes are buffered and send automatically in the
allowed maintenance intervals (granted by the OS every 1,2,4,6 hours in the
background).


We cannot work around these restrictions so pubs and events may be delayed
starting with Android 7. In my testing it worked fairly well however.

--
Alexander Rust

Am 11.09.2016 um 12:31 schrieb kvoit <notifications@github.com>:

Could you tell what you fixed? As jostick said, there are multiple issues
discussed here which ll fit under that headline.

—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub
<https://github.com/owntracks/android/issues/375#issuecomment-246173285>,
or mute the thread

**Comment by jostick** [comment]
Just want to confirm that the new BETA version fixes all my connection issues. I'm quite happy with now :)

**Comment by binarybucks** [comment]
I'm very happy to hear that

**Comment by Ricardosgeral** [comment]
With html private Owntracks disconnects after a while and it doesn't reconnect
