### ISSUE TITLE
Mobile iBeacons in Android

### ISSUE THREAD

**Issue by brusc** [owntracks/android#378]
I am attempting to configure ibeacons to work with Owntracks. Despite what I believe is ibeacon support, I am unable to publish GPS coordinates on ibeacons when I enter or leave an ibeacon zone. Am I missing something obvious? Is this not supported in the Owntracks Android app yet? Any timeline on when that update will be available? 

Thank you very much! Cheers!

**Comment by binarybucks** [comment]
This is not supported and we have no ETA for it.

On 18 Jun 2016, at 18:43, brusc <notifications@github.com> wrote:

I am attempting to configure ibeacons to work with Owntracks. Despite what
I believe is ibeacon support, I am unable to publish GPS coordinates on
ibeacons when I enter or leave an ibeacon zone. Am I missing something
obvious? Is this not supported in the Owntracks Android app yet? Any
timeline on when that update will be available?

Thank you very much! Cheers!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/owntracks/android/issues/378>, or mute the thread
<https://github.com/notifications/unsubscribe/AAvwFLj4hpYjnLpmI5Cw0ZFt38UotN4Oks5qNCBMgaJpZM4I4--4>
.

**Comment by brusc** [comment]
Can I ask why it isn't? It seems like most of the ibeacon support is already present. Isn't this as simple as appending the phone's GPS coordinates to the already support iBeacon MQTT message? There is a pretty high demand for this among the Home Automation community.

**Comment by brusc** [comment]
Hi, sorry to harp on this, I'm very interested in exploring mobile ibeacons with Android. I'm trying to figure out of there is a reason this hasn't been done yet. It seems like  Android Owntracks support for ibeacons is nearly completely with the exception that when the phone enters or leaves the ibeacon zone it isn't appending it's GPS coordinates. Am I missing something? Thank you much for your support and work on the project.  Cheers!

**Comment by hartmms** [comment]
I've been testing out beacons with Owntracks and they kinda work.  My beacons were ebay modules using the Nordic nRF52 series chips that I flashed with their default "beacon" firmware. I believe that firware supports the native Android beacon protocol in addition to Apple's iBeacon.  Using generic beacon scanner app I grabbed from google play, they are always visible when I'm in range.  

The main issue is that owntracks doesn't always "see" the beacons and report the event back via MQTT.  Other times, owntracks seems to loose the connection the my MQTT broker and gives up trying to reconnect. I have to manually initiate the connection.   I'm not sure this is a beacon issue, though.  Owntracks often does not even report my GPS coordinates back to my MQTT broker, even when it's connected.   

Now that I think about it, I wonder if the "doze" mode is sleeping the app and preventing it from phoning home. I also just updated to Nougat, so I'll re-install it and see if I get better behavior.

**Comment by binarybucks** [comment]
The current public version does not support Android 7. It does not reconnect nor does it handle Doze mode correctly. Please wait.

**Comment by hartmms** [comment]
Understood.  I'm up for testing any alpha/beta code you generate if that helps.

**Comment by abmantis** [comment]
Any update on this?

**Comment by capulo** [comment]
already closed, but...
you can use some workaround. just put small script on your mqtt server which will listen for beacon enter message and then send 'report location' cmd to device. so device will update its gps then

**Comment by jordandrako** [comment]
@capulo Do you mind sharing the script you mentioned?

**Comment by amarcine** [comment]
hi, i don't have script exactly for beacons, but similar. i have some mqtt topic which can be set via mobile phone, and then location request is sent...
note: latest version have some bugs... i can't request location for particular device so it will not works with latest version...

here is main functions which processing messages received from mqtt server. so when i set topic capo/request to '1' then report location is sent to device. sorry i can't publish whole program because there is lot of personal informaiton, but google for  paho.mqtt.client library and you will find some examples

def on_message(client, userdata, msg):
  payload=msg.payload.decode()
  if (msg.topic=="capo/request"):
    if (payload=="1"):
      send_requests()
      client.publish("capo/request", "0")

def send_requests():
  client.publish("owntracks/capo/sony/cmd", '{"_type":"cmd","action":"reportLocation"}')
