### ISSUE TITLE
Problems with building APK

### ISSUE THREAD

**Issue by friesenkiwi** [owntracks/android#395]
Hi, I wanted to update my local repository to - after long absence - continue working on the app (possibly trying to introduce a non-goolge-option ... https://github.com/owntracks/android/pull/239).
The new repository layout however seems to be a bit complicated? Maybe I did something wrong? There seem to be other people having trouble with it (https://github.com/owntracks/android/issues/386#issuecomment-240570715) so I open this issue.

I did a fresh clone in Android Studio 2.1 on Linux Mint, but afterwards, the IDE showed not much content. :-) So i manually opened the sub-folder 'project' as a new project window, which then complained about
> Error:Could not load wrapper properties from '[...]project/gradle/wrapper/gradle-wrapper.properties'.
> No value with key 'distributionUrl' specified in wrapper properties file '[...]/project/gradle/wrapper/gradle-wrapper.properties'.

So I copied the old gradle-wrapper.properties file, which had the following content:
```
#Mon Dec 28 10:00:20 PST 2015
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-2.10-all.zip
```
After Syncing the Project (Tool Window "Gradle"->"Refresh all Gradle Projects"), the files showed up correctly, i clicked "Run" to compile and deploy a debug version to my device connected via USB. It failed, because of 
> Error:(17, 33) error: package org.antlr.v4.runtime.misc does not exist
and subsequent
> Error:(278, 44) error: cannot find symbol class NotNull

So I added
`    compile 'org.antlr:antlr4-runtime:4.5.3'`

to the "dependencies" section in project/app/build.gradle, synced the project again and did "Run" which finally worked! (although the first start took some time)

I explained my steps here very detailed, in case someone has the same kind of problems. I could also do a pull request for the latter two changes, if you are interested? The first problem (empty project when using the repository root) is not solved by that, though, and I have no idea how to fix that. All those Gradle-wrapper, properties, idea-files make me kind of nervous...

Also, there is another problem: I can't get to build a final .apk via the Build->Build APK command. It always fails because of 
> Error:warning: Ignoring InnerClasses attribute for an anonymous inner class
> Error:(org.eclipse.paho.client.mqttv3.MqttAsyncClient$1) that doesn't come with an
> Error:associated EnclosingMethod attribute. This class was probably produced by a
> Error:compiler that did not target the modern .class file format. The recommended
> Error:solution is to recompile the class from source, using an up-to-date compiler
> Error:and without specifying any "-target" type options. The consequence of ignoring
> Error:this warning is that reflective operations on this class will incorrectly
> Error:indicate that it is *not* an inner class.

There is an upstream Issue filed: https://github.com/eclipse/paho.mqtt.android/issues/79 but it seems it may take a while until the new version gets released.
I tried hours to apply multiple remedys I found on the Internet (Stack Overflow and such) to make the Builder ignore those warnings, but nothing helped.
I tried adding 
```
    lintOptions {
        abortOnError false
        checkReleaseBuilds false
    }
```

into the "android" section in project/app/build.gradle
or adding a project.properties with `proguard.config=proguard-project.txt` and copying the old proguard-project.txt in
or adding a proguard-rules.pro with
```
-keepattributes EnclosingMethod
-keepattributes InnerClasses
-dontoptimize
```

but nothing helped :-( I'm a bit lost between all those dotfiles and conventions... it seems, the build process is not using any of them.

So, I managed to copy the installed debug apk from my phone to my own F-Droid repository. In case any of you would like to test a current version (latest repo), add https://fdroid.denk-nach-mcfly.de as a new repository to your [F-Droid App](https://f-droid.org/). I cannot promise to keep it always up to date there, but if any of you is using it and tells about it here, it will raise my motivation ;-) and I will try to deploy new packages once in a while. Also remember: The repo is not yet authorized by the maintainers ( @binarybucks ), it is not an official repo, the app might be in an unstable state currently! But, since it uses a different id (org.owntracks.debug), it should be installable in parallel to the official app from the play store.
I hope, it is OK with you @binarybucks and @jpmens ? I set up the repo mainly for myself in the first place, for debugging purposes, but if it might help somebody, I thought why not share? I don't want to be rude or offend anybody with providing this alternative source!

Cheers!

**Comment by binarybucks** [comment]
Could you please specify in one to two sentences what your exact problem
is?

Btw, the new HTTP mode will also rely on Google Play Services.

--
Alexander Rust

Am 18.08.2016 um 12:27 schrieb friesenkiwi <notifications@github.com>:

Hi, I wanted to update my local repository to - after long absence -
continue working on the app (possibly trying to introduce a
non-goolge-option ... #239 <https://github.com/owntracks/android/pull/239>).
The new repository layout however seems to be a bit complicated? Maybe I
did something wrong? There seem to be other people having trouble with it (#386
(comment)
<https://github.com/owntracks/android/issues/386#issuecomment-240570715>)
so I open this issue.

I did a fresh clone in Android Studio 2.1 on Linux Mint, but afterwards,
the IDE showed not much content. :-) So i manually opened the sub-folder
'project' as a new project window, which then complained about

Error:Could not load wrapper properties from
'[...]project/gradle/wrapper/gradle-wrapper.properties'.
No value with key 'distributionUrl' specified in wrapper properties file
'[...]/project/gradle/wrapper/gradle-wrapper.properties'.

So I copied the old gradle-wrapper.properties file, which had the following
content:

#Mon Dec 28 10:00:20 PST 2015
distributionBase=GRADLE_USER_HOME
distributionPath=wrapper/dists
zipStoreBase=GRADLE_USER_HOME
zipStorePath=wrapper/dists
distributionUrl=https\://services.gradle.org/distributions/gradle-2.10-all.zip

After Syncing the Project (Tool Window "Gradle"->"Refresh all Gradle
Projects"), the files showed up correctly, i clicked "Run" to compile and
deploy a debug version to my device connected via USB. It failed, because
of

Error:(17, 33) error: package org.antlr.v4.runtime.misc does not exist
and subsequent
Error:(278, 44) error: cannot find symbol class NotNull

So I added
compile 'org.antlr:antlr4-runtime:4.5.3'

to the "dependencies" section in project/app/build.gradle, synced the
project again and did "Run" which finally worked! (although the first start
took some time)

I explained my steps here very detailed, in case someone has the same kind
of problems. I could also do a pull request for the latter two changes, if
you are interested? The first problem (empty project when using the
repository root) is not solved by that, though, and I have no idea how to
fix that. All those Gradle-wrapper, properties, idea-files make me kind of
nervous...

Also, there is another problem: I can't get to build a final .apk via the
Build->Build APK command. It always fails because of

Error⚠️ Ignoring InnerClasses attribute for an anonymous inner class
Error:(org.eclipse.paho.client.mqttv3.MqttAsyncClient$1) that doesn't come
with an
Error:associated EnclosingMethod attribute. This class was probably
produced by a
Error:compiler that did not target the modern .class file format. The
recommended
Error:solution is to recompile the class from source, using an up-to-date
compiler
Error:and without specifying any "-target" type options. The consequence of
ignoring
Error:this warning is that reflective operations on this class will
incorrectly
Error:indicate that it is *not* an inner class.

There is an upstream Issue filed: eclipse/paho.mqtt.android#79
<https://github.com/eclipse/paho.mqtt.android/issues/79> but it seems it
may take a while until the new version gets released.
I tried hours to apply multiple remedys I found on the Internet (Stack
Overflow and such) to make the Builder ignore those warnings, but nothing
helped.
I tried adding

    lintOptions {
        abortOnError false
        checkReleaseBuilds false
    }

into the "android" section in project/app/build.gradle
or adding a project.properties with proguard.config=proguard-project.txt
and copying the old proguard-project.txt in
or adding a proguard-rules.pro with

-keepattributes EnclosingMethod
-keepattributes InnerClasses
-dontoptimize

but nothing helped :-( I'm a bit lost between all those dotfiles and
conventions... it seems, the build process is not using any of them.

So, I managed to copy the installed debug apk from my phone to my own
F-Droid repository. In case any of you would like to test a current version
(latest repo), add https://fdroid.denk-nach-mcfly.de as a new repository to
your F-Droid App <https://f-droid.org/>. I cannot promise to keep it always
up to date there, but if any of you is using it and tells about it here, it
will raise my motivation ;-) and I will try to deploy new packages once in
a while. Also remember: The repo is not yet authorized by the maintainers (
@binarybucks <https://github.com/binarybucks> ), it is not an official
repo, the app might be in an unstable state currently! But, since it uses a
different id (org.owntracks.debug), it should be installable in parallel to
the official app from the play store.
I hope, it is OK with you @binarybucks <https://github.com/binarybucks> and
@jpmens <https://github.com/jpmens> ? I set up the repo mainly for myself
in the first place, for debugging purposes, but if it might help somebody,
I thought why not share? I don't want to be rude or offend anybody with
providing this alternative source!

Cheers!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/owntracks/android/issues/395>, or mute the thread

**Comment by friesenkiwi** [comment]
General problem: Just checking out the current repo state leaves you with a "broken" build environment.
3 Sub-problems/causes:
1. The actual project files (project.iml/.idea/) are in the project/ directory (and there is no root level integration)
2. https://github.com/owntracks/android/blob/master/project/gradle/wrapper/gradle-wrapper.properties is empty
3. https://github.com/owntracks/android/blob/master/project/build.gradle is missing the `compile 'org.antlr:antlr4-runtime:4.5.3'` dependency
4. upstream org.eclipse.paho.client.mqttv3 is compiled with an old compiler, the warning about it lets the build fail. Overriding this via Gradle/ProGuard-Files doesn't work.

OT: Yes, I saw there is more entangling now. :) And I don't want to be a pita, that's why I first wanted to try to develop a bit before opening a PR etc. I totally get it that Google provides many nice services, which make life of a user and a developer much easier, I can't blame anyone (especially not you, because you are developing such a great app!) for using them. It's just ... I can't use the app in the current state, because my mobile OS (CyanogenMod) just doesn't provide those services (and I don't want to install them, because basically I like making my life a little bit complicated if that keeps me independent). I don't want to evangelize anyone! My use case would totally work without HTTP mode, so I don't need that feature. My goal would be to have Google independence as an optional kind of "graceful fail mode", where some features just don't work, but the basic (sending and displaying positions via MQTT) do without crashing the app.

**Comment by binarybucks** [comment]
Yes, I moved everything to the new AS project structure so some thongs
might still be broken. I'll fix things when I'm back from vacation next
week. However, l was able to import and compile the project just fine. The
errors with the Paho library exist for at least half a year so that is
nothing new really.

If you can submit a PR that fixes the project errors, I'll happily accept
it.

Re your Play issue: I understand your point. Even if you can submit a sane
PR that provides function without PS, it will roughly double our support
effort in the long run. If your version works really well and is easy to
maintain we could however talk about it.


--
Alexander Rust

Am 18.08.2016 um 13:48 schrieb friesenkiwi <notifications@github.com>:

General problem: Just checking out the current repo state leaves you with a
"broken" build environment.
3 Sub-problems/causes:
1. The actual project files (project.iml/.idea/) are in the project/
directory (and there is no root level integration)
2.
https://github.com/owntracks/android/blob/master/project/gradle/wrapper/gradle-wrapper.properties
is empty
3. https://github.com/owntracks/android/blob/master/project/build.gradle is
missing the compile 'org.antlr:antlr4-runtime:4.5.3' dependency
4. upstream org.eclipse.paho.client.mqttv3 is compiled with an old
compiler, the warning about it lets the build fail. Overriding this via
Gradle/ProGuard-Files doesn't work.

OT: Yes, I saw there is more entangling now. :) And I don't want to be a
pita, that's why I first wanted to try to develop a bit before opening a PR
etc. I totally get it that Google provides many nice services, which make
life of a user and a developer much easier, I can't blame anyone
(especially not you, because you are developing such a great app!) for
using them. It's just ... I can't use the app in the current state, because
my mobile OS (CyanogenMod) just doesn't provide those services (and I don't
want to install them, because basically I like making my life a little bit
complicated if that keeps me independent). I don't want to evangelize
anyone! My use case would totally work without HTTP mode, so I don't need
that feature. My goal would be to have Google independence as an optional
kind of "graceful fail mode", where some features just don't work, but the
basic (sending and displaying positions via MQTT) do without crashing the
app.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/owntracks/android/issues/395#issuecomment-240700323>,
or mute the thread

**Comment by friesenkiwi** [comment]
Ok, I added the PR, that makes things a bit easier. (2 and 3 solved) I have no solution yet for 1 and 4 though.

OT Google dependency: Thank you for being open to an addition sketched as above. I agree that maintainability is crucial and will therefore try to make changes as minimal as possible. Thinking about an option on the WelcomeActivity additional to "Fix" there might be a "Skip" with a warning, that  features will not be available in that case. A quick hack (see https://github.com/friesenkiwi/android/commit/db21f060db3de32c3301d9bc585e70ca01d213d8) proved, that the App would connect to the MQTT server and not crash. This way it's all up to the user who has been warned and it shouldn't introduce complexity. From there on I'd like to go step by step, not diverging too far from the master branch, pulling in all changes and possibly opening PRs for subtle differences, if that's OK?
But never mind now, have a good vacation!

**Comment by binarybucks** [comment]
You may open PRs for incremental changes but I'll merge them after a new
version with HTTP mode has been published. That feature is more urgent
currently ;)

--
Alexander Rust

Am 19.08.2016 um 10:26 schrieb friesenkiwi <notifications@github.com>:

Ok, I added the PR, that makes things a bit easier. (2 and 3 solved) I have
no solution yet for 1 and 4 though.

OT Google dependency: Thank you for being open to an addition sketched as
above. I agree that maintainability is crucial and will therefore try to
make changes as minimal as possible. Thinking about an option on the
WelcomeActivity additional to "Fix" there might be a "Skip" with a warning,
that features will not be available in that case. A quick hack (see
friesenkiwi@db21f06
<https://github.com/friesenkiwi/android/commit/db21f060db3de32c3301d9bc585e70ca01d213d8>)
proved, that the App would connect to the MQTT server and not crash. This
way it's all up to the user who has been warned and it shouldn't introduce
complexity. From there on I'd like to go step by step, not diverging too
far from the master branch, pulling in all changes and possibly opening PRs
for subtle differences, if that's OK?
But never mind now, have a good vacation!

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/owntracks/android/issues/395#issuecomment-240958907>,
or mute the thread

**Comment by friesenkiwi** [comment]
Fair enough! :)

**Comment by binarybucks** [comment]
I cannot build it  with the Antl dependency you added. Why was it needed?

**Comment by binarybucks** [comment]
Paho build errors should now be fixed with https://github.com/owntracks/android/commit/528bd2c9b7dbee5f5c6afc187a474b898512600d

**Comment by friesenkiwi** [comment]
Yes, the build succeeds now and I have no further problems developing.
The only thing unclear: If you do a fresh checkout of the root repo (https://github.com/owntracks/android.git) in Android Studio, the IDE will not find the actual project and leave you with an empty workbench. You'll need to open the project in the sub-folder manually. Maybe there could be some kind of root/include configuration? I tried to drop a settings.gradle with `include ':project'` but to no avail :-(

**Comment by binarybucks** [comment]
Are you trying to open the actual git root in Android Studio or the
project/ dir? The later works fine for me and is how it should work.
Opening the root should not and will not work because it just contains
the readme and changelog.

**Comment by friesenkiwi** [comment]
Well, it is working now for me, I only thought, it might be good for other people to know... ;-)
I was used to clone a project directly from a git repo (File->New->Project from Version control->Git). In this case, you need to make another step and open the project "a second time". But never mind.
