### ISSUE TITLE
Work without Google Play Services

### ISSUE THREAD

**Issue by grote** [owntracks/android#397]
Currently, OwnTracks [requires Google Play Services](https://github.com/owntracks/android/blob/master/project/app/build.gradle#L83). Therefore it is not Free Software and does not run on Android devices that don't have the Play Services installed.

I realize it is very convenient to use these libraries and often they are the technological superior choice. However, it makes the app non-free as it relies on proprietary libraries, only works on Google phones and leaks private data to google that is supposed to stay private.

At the moment it needs:
- [ ] com.google.android.gms:play-services-base
- [ ] com.google.android.gms:play-services-gcm
- [ ] com.google.android.gms:play-services-maps
- [ ] com.google.android.gms:play-services-location
- [ ] com.google.android.gms:play-services-places

For maps, [osmdroid](https://github.com/osmdroid/osmdroid#osmdroid) might be a suitable replacement. For the location, there is a native [LocationManager](https://developer.android.com/reference/android/location/LocationManager.html)  that could be used.

What is GCM and Places used for?

**Comment by binarybucks** [comment]
Before you blindly evangelize how bad Google Play Services, please familarize yourself with the code and the issues that are currently open and then come back. This issue IS being worked on by others. 

I understand that you're very personal about free software, but at the moment there are (*ghasp*) more important issues that I need to work on. 

If you're not satisfied with that answer, please a) submit actual CODE instead of links to projects we know about for a long time or b) leave. 

OwnTracks is developed in our free time because we think it might be useful to people. Nobody forces you to install it and nobody forces you to like it. You cannot use it on a device without Google Play Services and poeple most likely don't install Play Services to use OwnTracks. As I'm tired of repeating this over and over again, please read my other [comment](https://github.com/owntracks/android/issues/379#issuecomment-229000602).

Just that you know, at the moment I'm just at the brink of quitting this project and throwing everything into the wastebin because of people like you.

**Comment by grote** [comment]
@binarybucks Please relax a bit! I am developing apps in my free time as well and know very well that you will not spend hours of your personal time on something just because somebody told you so. I am not asking or demanding anything, just making you aware of a problem *I* see.

You don't need to agree and you can close the issue if you like. However, if somebody is working on it, maybe you can use this issue to coordinate that work and make it visible. If there's already another issue I didn't find, you can link to it and close this one as a duplicate.

I'm sorry if *people like me* are making you stop working on your project. As I said before, I don't want to attack you, just making you aware of something. If you are aware of that already and even pissed off about it, I am sorry, I didn't know that.

**Comment by binarybucks** [comment]
Thanks, apology accepted ;) 

We will keep Play Services in as default because it delivers quite some benefits (mainly battery optimizations) for casual users. If possible, there will be a fallback if no Play Services are installed or the user opts out of them. 

@friesenkiwi is working on some PRs for this.
