### ISSUE TITLE
Is the 'action' cmd unavailable for android

### ISSUE THREAD

**Issue by travisghansen** [owntracks/android#402]
The blog entry here says iOS only..http://jpmens.net/2016/02/15/switching-lights-with-owntracks-ibeacons-and-openhab/

However the documentation makes no mention of support for either platform.  Can I get an update of where things currently sit?

Thanks!

**Comment by binarybucks** [comment]
It's not supported on Android.

--
Alexander Rust

Am 04.09.2016 um 19:10 schrieb Travis Glenn Hansen <notifications@github.com
>:

The blog entry here says iOS only..
http://jpmens.net/2016/02/15/switching-lights-with-owntracks-ibeacons-and-openhab/

However the documentation makes no mention of support for either platform.
Can I get an update of where things currently sit?

Thanks!

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/owntracks/android/issues/402>, or mute the thread

**Comment by travisghansen** [comment]
OK thanks for the info!  PS I'd love to see the feature working on Android :)
