### ISSUE TITLE
Possible to set the minimum report interval

### ISSUE THREAD

**Issue by GermanBluefox** [owntracks/android#403]
I am using this nice app in connection with own MQTT Server and home automation.
But the reporting is rather strange. 
Can you extend settings with:
- minimum report interval (configurable). E.g. if set to 10 minutes, then no matter what happens, broker will get the report at least one in 10 minutes, even if nothing changed.
- minimum configurable distance (actually it is const 500m). I want to get oftener reports to detect if my wife or me arrived to home.

?
thank you,
Bluefox and 1800 users of ioBorker :)

**Comment by binarybucks** [comment]
Hi,

setting a minimum reporting interval is not possible. With Android 7 you can call yourself lucky if you get batched location updates every 1,2,4,6 hours in the background due to OS restrictions. 

Minimum distance that can be configured is 1m. 

Please note that the Android location services are optimized for battery use and therefore often neither accurate nor reliable. If you require precise realtime tracking, OwnTracks on a mobile phone is the wrong tool for the job.

Also, 0.6.14 has problems reconnecting, hence some delayed updates. There's no eta for a new version though.
