### ISSUE TITLE
If username is not set, app will not attempt connection but does not show why

### ISSUE THREAD

**Issue by rocketmonkeys** [owntracks/android#425]
App was saying that configuration was incomplete.  Put in hostname, tls, etc.  Completely unclear what was going on, no connections to the MQTT server.

Even though I had "Authentication" turned off, it would not even attempt to connect until I put in a dummy username.  Then the checkbox on upper right (What is that?) was enabled, and I saw a connection attempt.

This MQTT server had no auth (just for testing connectivity).  The app should attempt connection if Authentication is disabled and username is empty.  Right now it doesn't, but also doesn't tell the user why it's not working.

**Comment by binarybucks** [comment]
The username is required to build the base topic (and other things).
This is documented in our booklet.

The checkbox (re)connects. The cross disconnects.

Am 11.11.2016 um 21:09 schrieb rocketmonkeys <notifications@github.com>:

App was saying that configuration was incomplete. Put in hostname, tls,
etc. Completely unclear what was going on, no connections to the MQTT
server.

Even though I had "Authentication" turned off, it would not even attempt to
connect until I put in a dummy username. Then the checkbox on upper right
(What is that?) was enabled, and I saw a connection attempt.

This MQTT server had no auth (just for testing connectivity). The app
should attempt connection if Authentication is disabled and username is
empty. Right now it doesn't, but also doesn't tell the user why it's not
working.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/owntracks/android/issues/425>, or mute the thread
