### ISSUE TITLE
Last verion (1.1.5) for Android doesn't update location

### ISSUE THREAD

**Issue by dib0** [owntracks/android#431]
Hi!

Your app is great, but the last version (1.1.5) for Android doesn't update the location anymore. If I restart my device the location will update, but after that n update is processed by the application (other apps do get location updates).

If I open Owntracks I se the map with the right current location, by the pointer with my own device doesn't show on that location (just on the first one).

The report date/time also doesn't udpate.

I'm on an Android 5.1 device. The previous version worked without any problem. I hope you can fix this. If you need any more information or I can help you test something, please let me know.

**Comment by binarybucks** [comment]
Are you using websockts?

**Comment by dib0** [comment]
No, I use Mosquitto as a backend, but currently without websockets. I've been looking in to websockets, but haven't had the time.

Yesterday I installed the previous version 1.1.4, which works well.

**Comment by binarybucks** [comment]
I've uploaded a new version that reverts back to the 1.1.4 version of the
MQTT library. Please try that version.

Am 10.12.2016 um 14:41 schrieb Bas van den Berg <notifications@github.com>:

No, I use Mosquitto as a backend, but currently without websockets. I've
been looking in to websockets, but haven't had the time.

Yesterday I installed the previous version 1.1.4, which works well.

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/owntracks/android/issues/431#issuecomment-266209020>,
or mute the thread

**Comment by dib0** [comment]
Hi,

Versionb 1.1.6 didn't work either. Same problem as 1.1.5.

**Comment by binarybucks** [comment]
Will be continued in #430. It's the same issue probably.
