### ISSUE TITLE
Complete documentation on settings

### ISSUE THREAD

**Issue by elvaras** [owntracks/android#449]
I just read a bit through the documentation of the app and also installed the application on my phone. There are several settings where it's not clear what they do and how they work, and the settings booklet page is almost empty: [http://owntracks.org/booklet/features/settings/#settings](url)

Some examples:
- Reporting -> Automatic location reporting. I assume if this is on the location is reported on a regular basis (like every ten minutes?). If this is off, does the location get reported if, for example clicking on the "upload" symbol above the map? Is the location being tracked though not getting transmitted to the server?
- Reporting -> Extended data. I found some "extended data" for iOS in the documentation but not for Android. Does it currently make any difference to activate this option or not?
- Notifications -> Ongoing notifications -> Notifications (Display a notification to keep running). Does this mean that if this setting is off the application will not run when in the background?

**Comment by binarybucks** [comment]
You are right, the documentation for some settings is lacking a bit. 

- Automatic location reporting: If this is disabled, you have to hit the report button to send the current location. Otherwise, no location messages will be send. If enabled, location messages will be send depending on locator interval and locator displacement (device moved x meters in the laster y minutes). 
- Reporting -> Extended data: If enabled, some additional fields are added to the location messages, e.g. wifi, doze mode status. If there are some attributes in the future that don't fit the general location messages, they might be added there. I
- Ongoing notifications: If the ongoing notification is switched off, Android will kill the application in the background and you will not get any automated location reports. This is an OS limitation.

**Comment by elvaras** [comment]
Good explanation, thanks :)
