### ISSUE TITLE
Perform additional updates when transit ceases/stale data

### ISSUE THREAD

**Issue by warmfusion** [owntracks/android#456]
# problem

My location does not update to my _real_ location when I come to a stop after walking to my office as I have not walked exactly 500m since my previous update; this leaves the location being inaccurate and reduces the ability for regions to be useful.

# Proposal

When the application recognises itself as being 'in-transit' by having performed at least one update in the last 10 minute period, _or_ has a 'stale' location of at least 3 hours, one ore more additional location updates should be sent to the brokers after the defined period.

## Outcome

When I arrive at my office, my phone sees that the location hasn't moved by more than 500m and is in an 'in-transit' state so send another message indicating current location and mark the device as 'stationary'.

Alternativly, mark the device as 'slowing' and send 3 updates before being marked as 'stationary' so that the device might get a better fix on location before owntracks stops sending updates.

**Comment by binarybucks** [comment]
The idea is good and occurred several times already.  The problem ist, that it doesn't work that way. 
The application gets a callback from the OS (or the Play Services to be more precise) that the location changed. If that callback is received, the location is published. 

If no callback is received, we could wake up the device (which is an issue by itself) after 3 hours. However, the location API would then return the old stale location because it hasn't received a new location either in the meantime. 

We could, theoretically, create a new location request with a high-accuracy/high-power-usage properties after some hours. However, managing those in the background would be a huge PITA. 

If you're interested in knowing when you're at the office, you could just setup a region there that will trigger when you enter it. It uses a different API and is not bound to the callback dilemma mentioned above. If you need high accuracy of that, you could place a cheap BLE beacon at work.

**Comment by warmfusion** [comment]
I'd like to avoid having to purchase or deploy beacons - I'd like to include areas such as Train Stations or pubs for triggering actions/notifications.

How about using [LocationRequest](https://developers.google.com/android/reference/com/google/android/gms/location/LocationRequest) with different QoS levels based on the travling state.

For example, for each State;

* `Stationary` - PRIORITY_NO_POWER, Interval(600) (I assume this is the current setup?)
    * If moved > 500m - then `In-Transit`; else `Stationary`
* `In-Transit` - PRIORITY_BALANCED_POWER_ACCURACY, Interval(300)
    * Get a good position, checked every 5 minutes
    * If moved < 500m - then `Slowing`; else `In-Transit`
* `Slowing` - PRIORITY_BALANCED_POWER_ACCURACY, Interval(120)
    * Get a little more refined and we're slowing down so check a little more frequently to see when we stop
    * if moved > 200m - then `Slowing`; else `Stopping`
* `Stopping` - PRIORITY_HIGH_ACCURACY, (One-off)
   * A high precision check to get '`Stationary`' with detailed position
   * If moved > 100m - then `In-Transit`; else `Stationary`


Battery usage will increase, but only in the situation where the device is moving, with a spike when coming to stop to maintain accurate end-states.

Something like that anyway - the numbers are off the top of my head, and the state machine is equally adhoc, but for those who require/desire a little more granularity on the move, this may be an approach that could work?

**Comment by binarybucks** [comment]
> I assume this is the current setup
Depends on your settings. You can have everything between PRIORITY_NO_POWER to PRIORITY_HIGH_ACCURACY. The location request distance setting is locator displacement, and the interval is locator interval in the settings.  

I like the idea but the location API already has problems when juggling with the two location requests (foreground and background). I don't thing that throwing in another two (or six if you want to differentiate between foreground and background) is such a good idea. 

Additionally, the interval and distance settings for a location request don't work like you think. If you specify an Interval of 120s and 200m for a location request, you get a callback if the device moved 200m in the last 120s between now and the next 120s. You might get the callback earlier if another app requested the location with a higher accuracy or you might not get one at all because the device just moved 199m. 
Hence it is hard to say if the device moved >200m since the last request or not. It might have, but the last request might also be some hours ago. 

We'd be better off using the Play Activities API to determine if the device is stationary, walking or driving to adjust the locator settings dynamically. 

Did you try setting up a region in the app? I've seen solid results in detecting enter/leave events for various places. You don't need beacons for it to work. Without beacons it is mostly based on nearby WiFi networks.

**Comment by warmfusion** [comment]
Thank you for your detailed explanation; I'll try getting regions working a bit more effectivly for the time being. Still a shame that its not viable for an 'eventually accurate' implementation to be viable.
