### ISSUE TITLE
Beacon transitions - multiple leave events

### ISSUE THREAD

**Issue by tleegaard** [owntracks/android#489]
With my Nexus 5X I get multiple leave events even though the phone is home and hasn't moved. My wife's Huawei P10 doesn't seem to have the same issue, though we use the same settings:

`{"_type":"transition","tid":"TL","acc":0.0,"desc":"-home","event":"leave","lat":57.xxxx,"lon":9.xxxx,"tst":1496710243,"wtst":1495225053,"t":"b"}
{"_type":"transition","tid":"TL","acc":0.0,"desc":"-home","event":"leave","lat":57.xxxx,"lon":9.xxxx,"tst":1496710430,"wtst":1495225053,"t":"b"}
{"_type":"transition","tid":"TL","acc":0.0,"desc":"-home","event":"leave","lat":57.xxxx,"lon":9.xxxx,"tst":1496710492,"wtst":1495225053,"t":"b"}
{"_type":"transition","tid":"TL","acc":0.0,"desc":"-home","event":"leave","lat":57.xxxx,"lon":9.xxxx,"tst":1496710585,"wtst":1495225053,"t":"b"}
{"_type":"transition","tid":"TL","acc":0.0,"desc":"-home","event":"leave","lat":57.xxxx,"lon":9.xxxx,"tst":1496710710,"wtst":1495225053,"t":"b"}`

beaconBackgroundScanPeriode is set to 30 and beaconMode to 1.

**Comment by binarybucks** [comment]
Android versions?

**Comment by tleegaard** [comment]
Android O currently, but same thing was happening with 7.1.2

**Comment by binarybucks** [comment]
Due to new limitations on background services, many apps and libraries will not work as expected. 
The developers of the bracon library are working on support for Android 7 and above. Until a new version is released, you might see the above or other unexpected behavior. 

As a matter of fact, OwnTracks is also not fully compatible with Android 7 and above.

**Comment by tleegaard** [comment]
Oh, okay. Thanks for clarifying :-)
