### ISSUE TITLE
Android System thinks owntracks is misbehaving 

### ISSUE THREAD

**Issue by CheeseySandal** [owntracks/android#556]
* **App build number**: 2.0.0
* **Android version**: 8.1.0
* **Device**: Google Pixel 

Using HTTP into homeassistant. 

Blocking the ongoing notification results in another ongoing system notification saying that owntracks is using using battery. 

See https://github.com/owntracks/android/issues/555

Thanks.

**Comment by binarybucks** [comment]
Didn't you just close #555? 

Please post a screenshot of the new issue.

**Comment by CheeseySandal** [comment]
Yes, I closed #555 as I had the impression that the ongoing notification is required and wasn't getting removed, which is fair enough.  

This new issue is due to you writing

> The system provided „is using battery and data“ is there to uncover misbehaving apps. 

As I'm getting this with v2.0.0, by your own definition, v2.0.0 is misbehaving hence the new issue.


Thanks.


Screenshot
![screenshot_20180710-071234](https://user-images.githubusercontent.com/26098093/42493530-48dd015a-8415-11e8-943e-56cd33c58054.png)

**Comment by binarybucks** [comment]
The notification is required for apps to run in the background. If the notification is disabled, Android shows one instead to uncover hidden apps that might use battery and data without the users knowledge because there is no notification shown by the app that indicates this. 

Owntracks is behaving by the book becauses it shows a notification to indicate this. 
As you willingly disabled that, the placeholder shown by Android is not needed. 
Hence the option to also disable that. 

By no means does that indicate that the app itself is misbehaving.

**Comment by binarybucks** [comment]
Nest & Google Maps Location Sharing are Google apps, that might not be affected by this.
