### ISSUE TITLE
Beta 2.1.0 Feedback

### ISSUE THREAD

**Issue by binarybucks** [owntracks/android#569]
Please leave any issues for beta 2.1.0 builds here. 

**Build 21001**
Changelog: 
- Changed task scheduler to Android WorkManager. Location pings, MQTT keepalive and MQTT reconnect tasks are now have a lower limit of 15 minutes. 
- Waypoints database will be migrated from SQLite to ObjectBox during the first start. Please check if 
- Fixed several crashes during start. 
- Location messages now contain  `inregions` information

Known issues: 
- Contact details in the mapview are sometimes empty.

**Comment by ktpx** [comment]
Just wanted to say that my almost constant start crashes (when going out and back into the app) does not happen in this release. :dancer:

**Comment by jariha** [comment]
I get very inaccurate locations without first starting Google Maps.
After Google maps has been started the location in Owntracks is very accurate as well. 
I have set the minimum accuracy to 30.

**Comment by binarybucks** [comment]
@jariha the beta didn't change how locations are requested. 
What do yu mean by they are inaccurate? Is the accuracy of the location fix low (high radius) or do you get infrequent updates without starting Google Maps? 
What's your locator accuracy setting?

**Comment by jariha** [comment]
I have used only the beta version because the stable version was not very stable. 
All the locator accuracy settings are at High power. 
The Inaccurate locations is set to 30. 

With the 30 I don't usually get any location updated unless I start Google Maps. 
With higher setting I am all over the place like several hundred meters from where I actually am. 
I am using Nokia 6.1 with Android 8.1.0 if that helps.

Isn't the Inaccurate Locations this value in the output:
"location","acc":27. That is the accuracy radius of my location?

**Comment by binarybucks** [comment]
Ah you're supressing inaccurate locations with a accuracy lower than 30m. It could very well be that you just get a bad location fix and when Google Maps is started, the app can reuse the better fix then. 

Can you check if you have 
* Disabled WIFI
* Have disabled `Scanning always available` or set `Keep Wifi on during sleep` to never in th advanced Wifi settings? 
![grafik](https://user-images.githubusercontent.com/782356/46852542-a693f580-cdfb-11e8-9104-aa728e8fc1f8.png)

**Comment by jariha** [comment]
I have quite different settings in the Nokia. I have enabled the Open Network Nofications in the settings. 
I will check if that improves the accuracy.  I had already enabled the Wifi Scanning. 
Unfortunately this is no option for the Wifi sleep.

**Comment by begleysm** [comment]
I believe #568 is still an issue.  As in that thread, I have MQTT Snooper running on the same Android phone as OwnTracks.

I've had 2 different behaviors regarding updating while in a moving vehicle vehicle. In one case I get almost no updates being sent.  The blue dot doesn't update, and MQTT Snooper doesn't see any new messages.

In another case MQTT Snooper was showing a new message, exactly, every 30 seconds (which is a bit weird because I have it set to 100m & 60s).  However the OwnTracks app very rarely shows the updated position for my icon.  The little blue dot does update (which I think is tied to sending a message).

Additionally the manual upload button seems to reliably send a message (i get a new message immediately on MQTT Snooper).

I also noticed that when my Android app does update my icon's position, it doesn't so appear to, necessarily, be with the latest messages position.

**Comment by begleysm** [comment]
I had my wife update to the Beta release on her phone as well.  She noticed another bit of odd behavior.

She clicked in my icon under "Friends" which moved the map to my location and showed my location in the info bar at the bottom of the screen but my icon didn't get drawn on the map.  See the two screenshots below.  The first is from OwnTracks and the second is from Google Maps (proving the OwnTracks map centered on the correct location).

![signal-2018-11-06-180810](https://user-images.githubusercontent.com/1275999/48131687-27ed7500-e24e-11e8-8b32-1b902a4b93d3.png)
![capture _2018-11-07-05-25-56](https://user-images.githubusercontent.com/1275999/48131692-2d4abf80-e24e-11e8-93ca-ce7b3e3e7f50.png)

**Comment by binarybucks** [comment]
That’s basically the same issue you mentioned earlier ;)

**Comment by begleysm** [comment]
Perhaps.  Although I'm not so sure.  I *think* that my official set of issues refers to a cases where:
1. OwnTracks isn't uploading
2. OwnTracks isn't downloading

And that my last comment was about OwnTracks downloading but not updating the icon location.
1.  OwnTracks isn'twnwending updates
2.  O

**Comment by begleysm** [comment]
*Seemingly* out of nowhere I can no longer connect to OwnTracks.  I'm getting "javax.net.ssl.SSLHandshakeException: Chain validation failed" when I have my .crt uploaded to the Android OS and "javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found" when I have my .crt pointed to In OwnTracks -> Preferences -> Security -> Ca certificate.

As of now OwnTracks isn't communicating with the MQTT Server at all.  I'm not sure if this issue is related to my above problems or not.  I need to get this fixed before I can be confident I really still have problems.

I've read a few other issues (like #481) and it looks like there are 22 other certificate related issues that might help.  I'll report back after I address this problem.

**Comment by jpmens** [comment]
Is your certificate still valid (date/time)?

**Comment by begleysm** [comment]
Yes.  I didn't generate a new one (yet).  I reimported to the OS (and imported to OwnTracks) the same file I had emailed myself 3 months ago.  I just went to that email and checked the valid til and it's good until 3/17/2021.

**Comment by jpmens** [comment]
You shouldn't have to go through that trouble with Let's Encrypt issued certs.

**Comment by begleysm** [comment]
Roger.

I restarted my phone.  Didn't help.

I removed my User Certificate.  Didn't help.

I restarted my phone again.  Didn't help.

Status is still showing "javax.net.ssl.SSLHandshakeException: Chain validation failed"

MQTT Snooper is still able to connect to the server and download the last uploaded messages.

**Comment by binarybucks** [comment]
@begleysm you don't have to import the ca certificate into the app. Importing it into the system keystore should work fine. This is how I'm using LE certs or certs from a self signed ca. Importing it through the app can be used to circumvent any "your network might be monitored" notifications from Android. 

Regarding MQTT Snooper. That got me curious to enough to reproduce your issue. It's able to connect to my broker with a self signed certificate and a hostname that is different from the brokers common name even though I've removed the ca certificate from the device. My guess is that it doesn't validate either the certificate chain or certificate common name like Owntracks does. 

I suggest to use e.g. openssl to verify the CA setup of the broker. Also have a look at the broker log and check for any issues there.

**Comment by begleysm** [comment]
Thanks @binarybucks!  A solid lead.  I'll work on verifying the CA setup of the broker.  This will involve me getting a bit smarter on the details.

Currently I'm using the LetsEncrypt CertBot tool but I haven't dug into it that closely.

**Comment by begleysm** [comment]
Well, I don't know why things ever worked at all, but it looks like I was using chain.pem when I should have been using fullchain.pem in my broker configuration.

Now that I fixed that I'm getting all the updates that didn't happen over the last day. Pretty comical that they've all queued up :)  I can watch myself moving through town.  I've got about 8 hours worth of updates to go.

I think it's going to take a while for them all to come through.  After that is done I'll try to use the app "like normal" and report back my results.  I'm hopeful that this fixes my issue(s).  I'm not sure how much of my problems were related to my misconfigured Broker vs using the older release version of the Android App.

**Comment by binarybucks** [comment]
I've found that it is really neat for debugging messages. 

I've fixed an issue that didn't update the map icons when the app was in the background and one returned to it. Will push that to the beta channel soon. 
Are your map icons not updating when the app is open/active or just when the app is closed or the screen is locked?

**Comment by leranp** [comment]
The new version have a bug that there is no location update after reset my android unit, only when i open thr app it starts to send to the broker, android version 6.0, the auto start is on

**Comment by binarybucks** [comment]
Bild 21004 is rolling out on Google Play. Please report any problems with steps to reproduce in a new issue.
