### ISSUE TITLE
Unexpected transition trigger and waypoint timestamp

### ISSUE THREAD

**Issue by morenstrat** [owntracks/android#631]
* **App build number**: 2.1.1 (21101)
* **Android version**: 9  
* **Device**: Google Pixel 2

I just noticed that a transition with trigger value "l" was emitted after I created a waypoint and then published my location (which was within the waypoint's radius) manually. This trigger value is not documented here: https://owntracks.org/booklet/tech/json/#_typetransition - Also, the waypoint timestamp of that message seems to be wrong:

`{"_type":"transition","acc":16.0,"desc":"Home","event":"enter","lat":XXX,"lon":XXX,"t":"l","tid":"px","tst":1544358288,"wtst":1544357}`

**Comment by binarybucks** [comment]
Trigger l means the transition was triggered by a location update instead of a geofence transition detected by the device. With 2.x location updates are also checked against defined waypoints to assist in their accuracy. Before we had two different OS APIs workig separately. 

Which tst is off, the tst or wtst?

**Comment by binarybucks** [comment]
Docs are updated, thank you

**Comment by binarybucks** [comment]
wtst was treated as milliseconds internally.
Good catch.

**Comment by morenstrat** [comment]
Thanks (again)!

**Comment by binarybucks** [comment]
Fixed in 2.1.1
