### ISSUE TITLE
Big notification bar

### ISSUE THREAD

**Issue by defcon84** [owntracks/android#633]
* **App build number**: 2.1.1 (21102)
* **Android version**: 8.0.0
* **Device**: Samsung Galaxy S8

Why has the notification bar grown in the last update?
How can i enable the small bar again?

The small one was pretty unobstrusive and didnt leave a small icon on the top left as the big one does.

**Comment by binarybucks** [comment]
What do you mean by “grown”. Could you post a screenshot please?

**Comment by defcon84** [comment]
yes i can.
old small notification: https://i.imgur.com/AYOSZL3.jpg
new big notification: https://i.imgur.com/NQFdtL1.jpg
new icon: https://i.imgur.com/SldFBnF.jpg

**Comment by binarybucks** [comment]
Ah that’s likely a bug. I’ll have a look.

**Comment by binarybucks** [comment]
It seems that with support for the new notification channels, our "low priority" settings are mostly ignored. The good news is, that it is still easily configurable, just in a different place. 
Could you try setting the following: 

Long press the notification and hit "All Categories"
<img width="332" alt="grafik" src="https://user-images.githubusercontent.com/782356/49828697-d1171600-fd8c-11e8-9ad0-62fcf62f47d1.png">

Tap ongoing
<img width="367" alt="grafik" src="https://user-images.githubusercontent.com/782356/49828722-dffdc880-fd8c-11e8-99a0-e8a4dfa5d590.png">

Tap importance
<img width="369" alt="grafik" src="https://user-images.githubusercontent.com/782356/49828752-ebe98a80-fd8c-11e8-9ac0-733f7e5d640f.png">

Set to low
<img width="341" alt="grafik" src="https://user-images.githubusercontent.com/782356/49828759-f3a92f00-fd8c-11e8-8c1b-3fd2d75db791.png">

On my emulator and test device, this removed the little icon in the bar and collapsed the notification to the small size.

**Comment by binarybucks** [comment]
Apparently the low priority is ignored, because the service is now correctly started as a foreground service to receive constant location updates. 

The [docs](https://developer.android.com/reference/android/app/NotificationManager#IMPORTANCE_MIN) state that Min notification importance: only shows in the shade, below the fold. This should not be used with Service.startForeground since a foreground service is supposed to be something the user cares about so it does not make semantic sense to mark its notification as minimum importance. If you do this as of Android version Build.VERSION_CODES.O, the system will show a higher-priority notification about your app running in the background.

**Comment by defcon84** [comment]
It did indeed work! Did not know this. Thank you.

**Comment by binarybucks** [comment]
You're welcome. Thanks for pointing this out.
