### ISSUE TITLE
Deviceid /tracker id does not allow not alphanumeric characters

### ISSUE THREAD

**Issue by qwertangel** [owntracks/android#639]
* **App build number**: 2.1.2 (21201) 
* **Android version**: 9   
* **Device**: Pixel xl 2

When setting deviceid or tracker id , owntracks does not allow characters like "/". 
Google IOT  mandate deviceid/tracker ids to conform to special format which contains "/" characters.
Is there a workaround ?

**Comment by binarybucks** [comment]
DeviceId/TrackerId is alphanumeric because the default topics are constructed from it. It’s part of the Owntracks “protocol” and not specific to MQTT. It’s unlikely that Google mandates anything here 

You’re probably referring to the MQTT ClientId. Without further configuration it’s build from the device name/tracker ID. That can probably be configured to something non alphanumeric through the configuration editor (not tried it yet but it could be work). Try setting a value for the key `clientId`.

**Comment by binarybucks** [comment]
Closing for a lack of response
