### ISSUE TITLE
Question about deploying a local build of owntracks.

### ISSUE THREAD

**Issue by grheard** [owntracks/android#680]
I apologize if this isn't the correct place for this, but I have a question about deploying a local build of owntracks to my device. I currently have the release version of owntracks installed and configured. Do I need to remove that before deploying my local build? Will I need to reconfigure the app after deployment?

Thanks.

**Comment by binarybucks** [comment]
You probably need to uninstall the Play Store build first because it uses a different signing certificate. 

A debug build can be installed alongside but the work manager provider will conflict with the Play Store version unfortunately.

I suggest to export the config before uninstalling it so you can import it later

**Comment by grheard** [comment]
@binarybucks, thanks. My build is working as expected. Had a touch of trouble getting the maps to work. I initially added the map key to the project/gradle.properties file and not the project/app/gradle.properties file.
