### ISSUE TITLE
Owntracks actually do not accepts my own certifcate

### ISSUE THREAD

**Issue by EvilPingu** [owntracks/android#772]
I move data to my own server with my own certificate. Owntracks generates an SSLPeerUnverifiedException. The reason is that the certificate was created by myself. How can I prevent this? The certificate is installed in the Android.

* **App build number**: 2.1.3 (21302)
* **Android version**: Android 10
* **Device**: Google Pixel 3 XL

**Comment by growse** [comment]
Have you selected the certificate you installed on the device under "CA Certificate" on the Security page in the Preferences section?

**Comment by mathias-ewald** [comment]
I think @growse is correct in that you could solve it by providing the CA chain directly to Owntracks. Nonetheless, I found this issue because I might have hit the same problem but in a slightly different situation:

My MQTT service is secured with a Letsencrypt certificate. I use the same cert for a webserver and all browsers including the one on Android can verify its validity. Owntracks, though, fails at this. As soon as I provide the CA chain directly it works.

This and your situation make me think that the app is not using the local cert store!?

**Comment by growse** [comment]
Curious. I too use letsencrypt on an MQTT broker and don't have any issues. Could you generate a debug log and see if that has anything meaningful in it?

**Comment by alexte** [comment]
The difference might be the chain in the cert. I see different application needing or not needing the chain in the cert especially with let's encrypt. It often depends on the intermediate cert ("Let's Encrypt Authority X3") and if it was cached by other URLs your visited before.

You can test if your https server provides the needed intermediate/chain cert on https://www.ssllabs.com/

**Comment by growse** [comment]
Given we've rolled forward a number of significant changes, especially in how TLS is done, I'm going to close. Please re-open if you still have the issue on the latest version and can give me steps to reproduce.
