### ISSUE TITLE
Feature Request: Don't ignore significant changes.

### ISSUE THREAD

**Issue by codemunin** [owntracks/android#777]
Please add a feature for a significant-location-change to ignore the ignoreLowAccuracy.

The problem is, when I'm traveling fast in a train, the location isn't updated anymore because the Accuracy goes up to 3000 or more.

But when I don't set this option in my Hometown im Jumping in and out of the local zones, when im inside buildings.

I looked into the code and I think it could quickly realized like this:
```
package org.owntracks.android.services;
...
public class LocationProcessor {
...
    private boolean ignoreLowAccuracy(@NonNull Location l) {
        if (data.getLastPublishedLocation() != null && (l.distanceTo(data.getLastPublishedLocation()) > 2000)){
            return false;
        }
        int threshold = preferences.getIgnoreInaccurateLocations();
        return threshold > 0 && l.getAccuracy() > threshold;
    }
```

**Comment by growse** [comment]
There's a possibility that this could cause more problems than it solves. If the device gets a high-accuracy GPS fix followed by a low-accuracy Wifi fix, the second location could end up being a significant distance from the first. However, it's only "significant" because it's of such low accuracy. I'm not sure we should be publishing the second fix.

The problem here seems to be that you're after a way to differentiate between "I'm not moving significantly, disregard inaccurate locations" and "I know I'm moving, don't ignore inaccurate locations". Is that fair?

**Comment by codemunin** [comment]
Thanks for your answer. So it don't seems to be as easy as I hoped. I'm not much into Geolocations.

> There's a possibility that this could cause more problems than it solves. If the device gets a high-accuracy GPS fix followed by a low-accuracy Wifi fix, the second location could end up being a significant distance from the first. However, it's only "significant" because it's of such low accuracy. I'm not sure we should be publishing the second fix.

Okay i understand. Do you know how inaccurate it can get. Maybe we could crank threshold up to 10000m? 

> The problem here seems to be that you're after a way to differentiate between "I'm not moving significantly, disregard inaccurate locations" and "I know I'm moving, don't ignore inaccurate locations". Is that fair?

Yeah you got me. I have to travel by train for work and i turn off the inaccuracy Filter manual when i leave the house and turn it back on as I arrive. This step i want to automate.

Another idea I have is a second value for inaccurate locations outside a zone. So it's easy to get into the zone, but you need at least one accurate fix to get outside...

**Comment by growse** [comment]
> Okay i understand. Do you know how inaccurate it can get. Maybe we could crank threshold up to 10000m?

I'm not sure if there's a hard limit. I imagine it will vary by device, geolocation provider. The other issue to contend with here is that sometimes bad data can result in a fix that has both a *low accuracy* and is actually just plain *wrong*. I've seen fixes make wild jumps around to very far away locations (100s of miles) just because the provider has been confused about where I am. In this case, the accuracy filter is helpful as it doesn't end up publishing those.

> Yeah you got me. I have to travel by train for work and i turn off the inaccuracy Filter manual when i leave the house and turn it back on as I arrive. This step i want to automate.

I think there's something in this. The app provides quite a few different modes and config parameters and getting them right seems to involve a lot of trial and error. Worse, the "right" combination of settings seems to be context sensitive. E.g. "I'm on the train and plugged, therefore I want to be in move mode turning off the inaccurate filter". I'd want to explore how we can better make those sorts of changes available to other established automation apps (e.g. Tasker) and document clearly how to do it - I'm not sure we have that at the moment.

**Comment by codemunin** [comment]
> > Okay i understand. Do you know how inaccurate it can get. Maybe we could crank threshold up to 10000m?
> 
> I'm not sure if there's a hard limit. I imagine it will vary by device, geolocation provider. The other issue to contend with here is that sometimes bad data can result in a fix that has both a _low accuracy_ and is actually just plain _wrong_. I've seen fixes make wild jumps around to very far away locations (100s of miles) just because the provider has been confused about where I am. In this case, the accuracy filter is helpful as it doesn't end up publishing those.

I had such situations in the past, but the value for accuracy was nearly zero. So my observation was, if it's confused you can't trust the accuracy value either. So I think the original Idea is still possible and I want to try this. The feature should be optional for sure. Like you sad every device is different.

> > Yeah you got me. I have to travel by train for work and i turn off the inaccuracy Filter manual when i leave the house and turn it back on as I arrive. This step i want to automate.
> 
> I think there's something in this. The app provides quite a few different modes and config parameters and getting them right seems to involve a lot of trial and error. Worse, the "right" combination of settings seems to be context sensitive. E.g. "I'm on the train and plugged, therefore I want to be in move mode turning off the inaccurate filter". I'd want to explore how we can better make those sorts of changes available to other established automation apps (e.g. Tasker) and document clearly how to do it - I'm not sure we have that at the moment.

In my case it would be totally fine if i could access the low_accuracy filter with tasker.
Change the mode doesn't help, because the filter seems to be active in all modes.

**Comment by growse** [comment]
I hear that it'd be useful for you, the problem is that I'm not convinced it'd be useful for anyone else, so dedicating time to it is a tough sell. Also, we can't just keep adding configuration options to the UI, as it'll eventually become needlessly complex (it's already too complex I think).

**Comment by codemunin** [comment]
Nevermind. I will build this by myself.

If someone else is interested he can pm me.
