### ISSUE TITLE
Missing quick config option via app deep link (scheme) "owntracks://configuration?auth=true&url=https..."

### ISSUE THREAD

**Issue by slavino** [owntracks/android#834]
Just a proposal for improvement: https://developer.android.com/training/app-links/deep-linking

**Comment by growse** [comment]
What's the use case here?

**Comment by slavino** [comment]
> What's the use case here?
Especially for less technical folks/users.

- initial owntracks configuration for integration as 3rd party component of some bigger solution
- quick reconfiguration in case of need
- ability to interpret QR codes
- ... sky is the limit ;)

**Comment by growse** [comment]
I think there's value in being able to set up a config (say, on a web page that can generate a link / QR code) and then quickly import that onto the device. Saves faffing around typing on the config sections which isn't always ideal when starting from scratch. QR code support would be a nice benefit too.

I'd want to think a little bit about the user experience of what happens when they invoke this url. Things like:

- We'll want to prompt the user to confirm that they want to change their config. How far do we go in showing them what will change?
- What happens if the config specifies a client TLS certificate name that they don't have on their device? Silently failing here doesn't seem like a good option, so just need to figure out how to tell the user what's going on without confusing them (especially if they're non-technical).
- How do we alert the user that such URLs (assuming they have unique, per-device settings like MQTT credentials and clientId) are very non-sharable?

**Comment by ckrey** [comment]
We implemented deep lins in the iOS app for setting up [iBeacons](https://owntracks.org/booklet/tech/qr/)
The docs are a bit out of date because the actual QR reader is no longer part of the app, but scheme `owntracks:` still supports the definition of iBeacons

For configuration we support opening `.otrc`  or `.otrw` files in the app. In this case, the is no specific user prompt currently.

**Comment by slavino** [comment]
> We implemented deep links in the iOS app for setting up [iBeacons](https://owntracks.org/booklet/tech/qr/)
> The docs are a bit out of date because the actual QR reader is no longer part of the app, but the scheme `owntracks://beacon?-...` still supports the definition of iBeacons
> 
> For configuration we support opening `.otrc` or `.otrw` files in the app. In this case, the is no specific user prompt currently.

I referenced Android for application deep linking (as I'm not iOS fan).

I will check the approach with "application/otrc" header and/or ".otrc"/".otrw" suffix for integrating OwnTracks into a design I work on.

PS: Map selector might be of huge benefit (at least ability to switch to satellite map or even better  other map vendor).
PS2: Is there an option to embed owntracks as library into another Android app and distribute it with "closed" sources?

**Comment by ckrey** [comment]
We try to keep iOS and Android version features equivalent.

**Comment by slavino** [comment]
https://owntracks.org/booklet/tech/json/

Let me dive a bit deeper

so opening a downloaded '.otrc' file (persisting in Downloads): 
{"_type":"cmd","action":"setConfiguration","configuration":{"_type":"configuration",...}

and convenient browser level choice to open URL
owntracks://cmd?action=setConfiguration&configration=`urlencode(jsonConf)`

might do the same thing in iOS and Android? Right?

**Comment by ckrey** [comment]
@slavino regarding your question about embedding OwnTracks:
We think the Eclipse license is quite clear (see below).
But you may talk with us about your project on support@owntracks.org

![3683EE84-151E-4F62-AC23-2F6B68F58338](https://user-images.githubusercontent.com/4027289/83661832-02aa1f80-a5c7-11ea-907a-a2e782fb558d.jpg)

**Comment by growse** [comment]
Fixed in 828220a8db26c62ca2905126943ea5d5d4bfd489
