### ISSUE TITLE
Request for string translation to FR

### ISSUE THREAD

**Issue by jpmens** [owntracks/android#844]
@mekhaba back in #817 you helped us translate some strings to French. May we request your help again for a few more? We're ready to cut a new release, and have a few strings which need some love.

Here they are:

```xml
<missing>
  
<string name="preferencesKeepaliveValidationError" formatted="true">Keepalive should be a minimum of %d</string>
<string name="title_exit">Exit app</string>
<string name="preferencesLocatorInterval">Location interval</string>
<string name="preferencesLocatorIntervalSummary">Interval between location updates</string>
<string name="preferencesLocatorIntervalDialog">How often should locations be requested from the device (seconds)</string>
<string name="preferencesMoveModeLocatorInterval">Location interval (Move mode)</string>
<string name="preferencesMoveModeLocatorIntervalSummary">Interval between location updates in Move mode</string>
<string name="preferencesMoveModeLocatorIntervalDialog">How often should locations be requested from the device whilst in Move mode (seconds)</string>
<string name="preferencesDebugLog">Debug log</string>
<string name="monitoring_mode">Monitoring</string>
<string name="preferencesClientId">Client ID</string>
<string name="status_endpoint_state_hint">Endpoint state</string>
<string name="status_endpoint_state_message_hint">Endpoint state message</string>
<string name="status_endpoint_queue_hint">Endpoint queue</string>
<string name="status_last_background_update_hint">Location service last background update</string>
<string name="status_background_service_started_hint">Background service started</string>
<string name="status_battery_optimization_whitelisted_hint">Battery optimization whitelisted</string>
<string name="clear_log">Clear</string>
<string name="viewLogs">View Logs</string>
<string name="logViewerActivityTitle">Logs</string>


</missing>
```

Your assistance would be greatly appreciated! :-)

**Comment by mekhaba** [comment]
OK, It's a pleasure :)

**Comment by mekhaba** [comment]
Re,
As promised, in attached file you find the translation (name file : missing_fr_translation.txt ).

I tested them in the new version (master version) and all seems good. take a look for attached image. 
The new features, are good  ( **Exit application** to avoid background process and **Logs** ).

You have to note that I ignored some keys because, they were duplicated, the keys are : 
<string name="title_exit">Quitter l\'application</string>
<string name="preferencesLocatorInterval">Intervalle de localisation</string>
<string name="preferencesLocatorIntervalSummary">Intervalle entre les mises à jour de localisation</string>
<string name="preferencesLocatorIntervalDialog">À quelle fréquence les localisations doivent-ils être demandés à l\'appareil (secondes)</string>

I am ready when needed.
thanks and have a good day. 

[missing_fr_translation.txt](https://github.com/owntracks/android/files/5010277/missing_fr_translation.txt)

![journal](https://user-images.githubusercontent.com/294111/89100677-d9ecad80-d3f0-11ea-8e11-7199f65a866b.png)

**Comment by jpmens** [comment]
@mekhaba that is wonderful, thank you very much! I notice you've not translated the word `Endpoint` which is hard to do. We'll leave it as such until somebody has an idea on how to name that in French. :-)

**Comment by mekhaba** [comment]
@jpmens, sorry I forgot to mention it. 
the `Endpoint` in french is  `Point de terminaison`. I couldn't really find the good translate about it.
I'll continue looking for, once it's OK I'll signal you.

**Comment by eghetto** [comment]
Am 1. August 2020 1:20:18 nachm. schrieb JP Mens <notifications@github.com>:

**Comment by jpmens** [comment]
@eghetto ???
