### ISSUE TITLE
HTTP Basic Authentication reported as not working

### ISSUE THREAD

**Issue by jpmens** [owntracks/android#851]
Im opening this issue as a reminder to test basic authentication in HTTP mode. According to https://github.com/owntracks/talk/issues/103:

> we could not get the basic authentication to work (in HTTP mode)

**Comment by linusg** [comment]
Just for the record, I do have exactly this setup and it works fine for me.

```
$ curl -I https://my.owntracks.host/pub
HTTP/2 401 
content-type: text/plain
www-authenticate: Basic realm="traefik"
content-length: 17
date: Wed, 09 Sep 2020 20:25:45 GMT
```

- OwnTracks Recorder 0.8.6 (Docker) behind Traefik 2.2.8 (Docker)
- OwnTracks Android client 2.1.3 (21302) on Android 9/10

<img src="https://user-images.githubusercontent.com/19366641/92649700-54a7c300-f2e3-11ea-813d-d97fff355e57.png" width="300">

**Comment by jpmens** [comment]
Thank you, @linusg, for confirming this.

**Comment by boogymantoo** [comment]
Hello again,

First of all, thanks for the prompt response.

Could we dive a bit deeper then, on **how** owntracks provides support for basic auth? Here is some more detail about my setup, my assumption on how owntracks implements this, and a log showing that it does not work according that assumption.

- in the owntracks configuration, i have:
  + auth is true
  + host url is https (with valid certificate, from letsencrypt)
  + username is 'Chris' and i use a (weak, for this test) password

- my assumption is that owntracks will now pro-actively insert this http header -> Authorization: Basic [b64 string here]

- but when i get all http headers (in the php context) there is no such header; here the list of all headers i get:
  + Accept-Encoding => gzip
  + Connection => close
  + Host => [removed the value]
  + Content-Length => 145
  + Content-Type => application/json; charset=utf-8
  + Cache-Control => no-cache
  + X-Limit-D => 999A
  + X-Limit-U => Chris
  + User-Agent => Owntracks/21302

Many thanks,
Chris.

**Comment by jpmens** [comment]
I've configured the following running under Apache, and Basic auth works as I'd expect it to:

### .htaccess

```
AuthUserFile /Users/jpm/Sites/auth/ht.pw
AuthType Basic
AuthName GetOUT
Require valid-user
```

### loc.php

```php
<?php
        header("Content-type: application/json");

        $payload = file_get_contents("php://input");
        $fp = fopen("/tmp/loc.out", "a");

        foreach (getallheaders() as $k => $v) {
                        fprintf($fp, "%s: %s\n", $k, $v);
        }
        fprintf($fp, "\n");
        fwrite($fp, $payload);
        fclose($fp);
...
```


### access log

```
192.168.1.145 - jjolie [10/Sep/2020:10:58:34 +0200] "POST /~jpm/owntracks/auth/loc.php HTTP/1.1" 200 140
```

### loc.out

```
User-Agent: Owntracks/22056
Authorization: Basic ampvbGllOnBhcmlz
X-Limit-U: jjolie
X-Limit-D: s8
Cache-Control: no-cache
Content-Type: application/json; charset=utf-8
Content-Length: 169
Host: 192.168.1.140
Connection: Keep-Alive
Accept-Encoding: gzip
```

I configured OwnTracks on Android with the URL (`http://192.168.1.140/~jpm/owntracks/auth/loc.php`) and set username (`jjolie`), password (`paris`), device id (`s8`) and tracker-ID (`S8`).

**Comment by jpmens** [comment]
I note you are using version `21302`. Can you test with the latest beta from the Play Store, please?

**Comment by boogymantoo** [comment]
Re-bonjour @jpmens ,

It is a real joy to see such responsiveness - thanks.

Now I believe I owe an apology: thanks to the convincing posts here-above, I re-visited this 'problem', only to find out that it is due to some bizarre behavior of Apache + FastCGI + PHP.

Apparently, by default the http authorization header **is not passed on** to the php runtime context. That's the reason why I don't see that header in the php context.

But Google is your friend - once I knew what I was looking for, the solution was found quickly enough. Adding the following lines in the apache config (for the virtual https host in question) does the trick (the rewrite engine must of course also be enabled):

`RewriteCond` %{HTTP:Authorization} ^(.+)$
`RewriteRule` .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]

So, if like me you want to:
* avoid impact on the apache 'username/password' settings
* handle the username/password validation entirely in the php context
then you need to **force** apache to pass the http authorization header in the downstream flow, like above

Note that I still used 21302 - so it is confirmed to work in that version. Will upgrade one of the coming days.

Thanks again,
Chris.

**Comment by jpmens** [comment]
I'm glad you found the reason; it was bound to be something **cough** easy **cough**. :-) 

Closing this now as solved; thank you for the feedback!
