### ISSUE TITLE
Time of last location fix

### ISSUE THREAD

**Issue by gitmayer** [owntracks/android#868]
As part of the new 2.2.0 update it was noted that 'tst' is now the current time of the message and not the last location fix.  While this is a great addition, is there a way to add the last location fix time to the extended data?  I was previously (still am) using the tst field as part of the primary key to eliminate duplicate messages being logged as unique location fixes.  From the current data received, I don't see how else I could determine this location time. Thanks.

**Comment by growse** [comment]
It's a fair q. We changed the meaning of `tst` in the Android app earlier this year to bring its meaning in line with the other message types. There were also issues for people who were using `tst` as a primary key who wanted specifically to capture multiple messages with the same fix time having those being rejected, so it seems that there's a conflict in requirements.

I can absolutely see the case for wanting the fix timestamp as well as the message timestamp. This is an easy technical fix, but I'd want to get a consensus from @jpmens and @ckrey that it's a sensible change to the model.

**Comment by triplepoint** [comment]
Could we leave it the way it is, for consistency of meaning for `tst`, and add a new `loc_tst` field to contain the last location fix? Clearly people are finding value with both timestamps.

**Comment by growse** [comment]
Obviously agree that if there's value in having both "time-of-fix" and "time-of-message", then we should look to include both. The issue here is the semantic meaning of `tst`, which historically (according to the booklet) should mean "time-of-fix". 

I see the consistency argument, but there's other message types for which `tst` also doesn't mean "time-of-message". For example, for `"_type": "transition",` the `tst` field is the "Timestamp at which the event occured" - this makes sense when you look at it alongside the other fields like `lon`, `lat` etc. which are all specific to when the event occurred.

**Comment by triplepoint** [comment]
Either works, as long as it's documented what the fields mean in different contexts. I can't think of anywhere where I currently try to use `tst` without first being aware of the type. I think any solution will be fine.

**Comment by growse** [comment]
Should be in 2.2.1. Thanks!
