### ISSUE TITLE
Consider informing user and/or dropping HTTP POSTs on 4xx errors

### ISSUE THREAD

**Issue by jpmens** [owntracks/android#936]
As shortly discussed and reported in https://github.com/owntracks/ios/issues/663 we might consider informing the user of HTTP `4xx` codes upon HTTP POST requests, and optionally dropping the payload completely until the client and server have solved the issue.

As seen in the case of our client with a Traccar server, not deleting a `_type: dump` request will basically disable the client forever.

Note that this affects HTTP only.

**Comment by jpmens** [comment]
Linking https://github.com/owntracks/ios/issues/665 to show UI @ckrey implemented for iOS

**Comment by growse** [comment]
So it feels like there's a maybe more general principle here, about messages, retries and failures which might read to a more general implementation. 

As I understand it, the current implementation queues messages for sending, and on failure to send will re-queue at the front and then retry at some point later. This allows for patchy network coverage and temporary outages to not cause data to be lost.

As identified in the Traccar issue though, the downside of this approach is when a failure is permanent for a specific message, the whole queue is blocked forever. The problem here is how does the client distinguish between a failure that might be temporary and retried, vs one that in permanent?

Trusting that the server is giving you accurate error codes doesn't always work (4xx could be caused by a temporary misconfiguration or Auth backend failure), so if the aim is to preserve as much data as possible, I'm not sure that just dropping the message on 4xx is the right thing to do. 

Would a better implementation be to have a retry budget for *all* messages? In other words, if a message delivery fails, the budget is decremented and delivery is retried later. Once the budget hits zero, the message in discarded. We could even then decrement by different amounts depending on the failure: if the endpoint is unreachable, then we maybe decrement the budget less than if we get a 4xx. This should give us room for a lengthy queue if the device goes out of network coverage, but be. About more aggressive in discarding messages after fewer retries if the endpoint is reachable but returns an error.

I don't want to over-complicate this, but I also don't want to be unnecessarily discarding messages due to temporary failures.

**Comment by jpmens** [comment]
Taking your _budget_ idea a step further (and I hope this isn't over-complicating the over-complication), would different budgets for different types of messages make sense?

Type=location is likely our most important message so it would have a high budget. Type=dump is something a user explicitly triggers so they are "at the device" when it occurs and a quite low budget would be very acceptable.

**Comment by growse** [comment]
Yes, agree. I can start to flesh out the implementation in a PR.
