### ISSUE TITLE
App Permission ACCESS_BACKGROUND_LOCATION for Android API 29

### ISSUE THREAD

**Issue by alexte** [owntracks/android#969]
* **App build number**: 2.3
* **Android version**: 11
* **Device**: Pixel 4a 5G

Since Android API 29 there is a permission called "android.permission.**ACCESS_BACKGROUND_LOCATION**"

https://developer.android.com/training/location/permissions

Without requesting this permssion it seems that android asks the user for "Allow only while using the app" only.
With this permission the user can opt for "Allow all the time" 

Owntracks doesn't currently ask for Location Updates "all the time" if I read the code correctly.
eg Google Maps does, if location reporting is activated

![Screenshot_20210401-102653](https://user-images.githubusercontent.com/7724992/113268972-4699ae00-92d8-11eb-96ec-d5433c9f2493.png)

**Comment by growse** [comment]
We don't need background location because OT runs a foreground service. It's poorly labelled, but in this case, "allow while app is in use" includes foreground services.

`ACCESS_BACKGROUND_LOCATION` is labelled as a "dangerous" permission anyhow (https://developer.android.com/reference/android/Manifest.permission#ACCESS_BACKGROUND_LOCATION) and Google are really tightly locking down and restricting which apps can ask for it. Obviously Google Maps gets a free pass. In other words, there's a whole load of confusing hoops I don't have time to jump through to get a permission we don't need.

**Comment by alexte** [comment]
ok. even google maps must ask the user twice and bounces the user into the settings dialog to get this permission. as does the automate app for example. 
I fear that OTs method of doing foreground location with permanent notification is a hack that will soon be shut down by google. I had difficulties to keep OTs running after upgrade to Android 11. battery optimization and so on...

**Comment by growse** [comment]
A foreground service is currently the only way I know to receive locations relatively frequently without having an activity open and being actively used (e.g. in move mode). You can get locations with a background service and the right permission, but they'll only arrive a few times per hour.

For MQTT users who need a persistent connection, I seem to remember this not working in the context of a background service either (android just kills it after a while).

For the moment, it's here to stay. We'll have to wait and see how Google evolves this.

**Comment by alexte** [comment]
Thanks for clarification, and thanks for your great work.

For Pixel 4a (Android11) users who have the same issues, of not receiving location updates in "significant changes" mode,
I described my workarround in #970
