### ISSUE TITLE
send another data beside location.

### ISSUE THREAD

**Issue by anicej** [owntracks/android#977]
Hi,
Thanks for making this app open source.
I want to send other information like BLE  data such as UUID, RSSI, name by this application with BLE type beside location or separately but I can't find where I can add this data to send. I think what I need is like beacon that is implemented in owntrack ios version.
please help me by keywords or functions name.

**Comment by growse** [comment]
Hi - we removed beacon support from Android a while back because it was awful, buggy and generally useless. We may look at re-adding this in the future if support becomes better, but you're welcome to work on it and send a PR if you can get something that's reliable.

There's a bunch of libraries out there that I don't think existed before (https://altbeacon.github.io/android-beacon-library/) so that might be worth a look.
