### ISSUE TITLE
Log is rapidly filled with errors - ResourceType: beyond entry count.

### ISSUE THREAD

**Issue by grumpazoid** [owntracks/android#998]
* **App build number**: 2.3.0(23024)
* **Android version**: 7.0
* **Device**: xiaomi redmi note 4

Everything appears to work as expected  but the log is constantly flooded with:
05-15 10:32:23.154 18930 18930 W ResourceType: For resource 0x7f110278, entry index(632) is beyond type entryCount(177)
05-15 10:32:23.154 18930 18930 W ResourceType: For resource 0x7f110278, entry index(632) is beyond type entryCount(177)
05-15 10:32:23.154 18930 18930 W ResourceType: For resource 0x7f11027a, entry index(634) is beyond type entryCount(177)

Same wether using HTTP or MQTT 
Redmi note 6 phone does not have this problem.

Anything I can do? Thanks.

**Comment by growse** [comment]
Yeah, this is an annoying artifact of android sometimes gathering up a load of unrelated log messages under the process's ID when using logcat. The current version that logs are displayed is by simply gathering / streaming the logcat output filtering by the process. Different devices seem to behave somewhat differently in this.

Suffice to say, I've re-worked how logs are collected and displayed in the next version (2.4.0) - see commit 7e2f1970, avoiding the use of logcat alltogether. So this should be fixed in the next version. Still a few other bugs to be worked out in that as there's some fairly major changes, but hoping it should be along soon.

**Comment by grumpazoid** [comment]
@growse Great to hear a fix is planned.  Thanks
